/**
 * Le parole del video "il giro completo", nelle undici lingue.
 *
 * 🔴 GENERATO da scripts/prepara-giro.py: non si scrive a mano.
 * Le sorgenti stanno in geotapp-reel (testi.ts per le scritte del
 * montaggio, voce_giro.py per il parlato, voce.ts per i tempi).
 *
 * La trascrizione sta qui, e non solo nei .vtt, perche' la pagina del
 * video la mostra scritta: e' il testo che Google puo' leggere, e serve a
 * chi non puo' o non vuole guardare ottanta secondi di filmato.
 */
import type { LinguaGiro } from './video-giro';

export type VoceTrascrizione = { da: number; testo: string };

export type ContenutoGiro = {
  titolo: string;
  passi: string;
  nota: string;
  atto: string;
  atti: string[];
  chiusa: string;
  trascrizione: VoceTrascrizione[];
};

export const GIRO_CONTENUTI: Record<LinguaGiro, ContenutoGiro> = {
  it: {
    titolo: "UN TURNO, DALL’INIZIO ALLA FINE",
    passi: "TIMBRATURA · DUE PROVE · IL REPORT · LA VERIFICA",
    nota: "Un telefono vero e uno schermo vero. Niente è ricostruito.",
    atto: "ATTO",
    atti: [
      "Si apre il turno",
      "Il guasto, fotografato",
      "Arriva da sola",
      "Due ore dopo",
      "Si chiude il turno",
      "La commessa si chiude",
      "Verificato senza di noi",
    ],
    chiusa: "Il lavoro lascia un documento che chiunque può verificare — anche fra anni, senza chiederlo a noi.",
    trascrizione: [
      { da: 0.3, testo: "Un turno, registrato mentre accade." },
      { da: 3.3, testo: "In cantiere, un tocco apre il turno." },
      { da: 5.793, testo: "Cinque secondi dopo, in ufficio lo schermo lo mostra già al lavoro." },
      { da: 10.433, testo: "Nessuno ha toccato niente." },
      { da: 13.3, testo: "La prova comincia da una foto." },
      { da: 15.364, testo: "La fotocamera si apre nell'app: niente galleria." },
      { da: 20.3, testo: "Due interruttori scattati, cavi fuori dalla canalina." },
      { da: 23.774, testo: "Scrive quello che ha trovato e invia." },
      { da: 28.3, testo: "Ed eccola, in ufficio." },
      { da: 29.791, testo: "Quella pagina non l'ha toccata nessuno." },
      { da: 33.3, testo: "Due ore dopo, lo stesso quadro è rimesso a posto." },
      { da: 37.225, testo: "Seconda foto." },
      { da: 39.3, testo: "Interruttori riarmati, cavi nella canalina, quadro chiuso." },
      { da: 43.668, testo: "Inviata, come la prima." },
      { da: 46.3, testo: "Ecco le prove." },
      { da: 47.505, testo: "La seconda è appena arrivata." },
      { da: 50.3, testo: "Timbra l'uscita: due ore e cinquantatré." },
      { da: 52.981, testo: "Le due timbrature dicono Provato." },
      { da: 55.192, testo: "La giornata è coperta." },
      { da: 60.3, testo: "Il lavoro è finito." },
      { da: 61.683, testo: "Un pulsante chiude la commessa e rilascia il report." },
      { da: 65.8, testo: "In un solo ZIP." },
      { da: 67.109, testo: "Chiuso e sigillato." },
      { da: 69.3, testo: "E il cliente lo verifica da solo." },
      { da: 71.858, testo: "Una pagina HTML, offline, ricalcola ogni impronta." },
      { da: 77.3, testo: "Un report che chiunque può verificare." },
    ],
  },
  en: {
    titolo: "ONE SHIFT, END TO END",
    passi: "CLOCK IN · TWO PROOFS · THE REPORT · THE CHECK",
    nota: "A real phone and a real screen. Nothing is reconstructed.",
    atto: "ACT",
    atti: [
      "The shift opens",
      "The fault, photographed",
      "It lands by itself",
      "Two hours later",
      "The shift closes",
      "The job is closed",
      "Checked without us",
    ],
    chiusa: "The work leaves a record anyone can check — years from now, without asking us.",
    trascrizione: [
      { da: 0.3, testo: "One shift, recorded as it happened." },
      { da: 3.3, testo: "On site, one tap starts the shift." },
      { da: 5.605, testo: "Five seconds later the office screen already shows him at work." },
      { da: 9.875, testo: "Nobody refreshed the page, nobody typed anything in." },
      { da: 13.3, testo: "The proof starts with a photo." },
      { da: 15.121, testo: "The camera opens inside the app: no gallery, so the picture can only be taken now." },
      { da: 20.3, testo: "Two breakers tripped, cables out of the trunking." },
      { da: 23.39, testo: "He writes what he found and sends it." },
      { da: 25.723, testo: "The phone queues it, then it goes." },
      { da: 28.3, testo: "And there it is, in the office." },
      { da: 30.256, testo: "Nobody touched that page." },
      { da: 33.3, testo: "Two hours later, the same board, put right." },
      { da: 36.393, testo: "Second photo, taken the same way." },
      { da: 39.3, testo: "Breakers reset, cables back in the trunking, the board tested and closed." },
      { da: 44.216, testo: "Sent, like the first one." },
      { da: 46.3, testo: "There are the proofs." },
      { da: 47.498, testo: "The second one has just landed." },
      { da: 50.3, testo: "He clocks out: two hours and fifty-three minutes." },
      { da: 53.311, testo: "In the office both movements read Proved." },
      { da: 55.83, testo: "The photos got there, so the day is covered." },
      { da: 60.3, testo: "The work is done." },
      { da: 61.45, testo: "One button closes the job and releases the report." },
      { da: 65.8, testo: "In one ZIP." },
      { da: 66.913, testo: "Closed and sealed." },
      { da: 69.3, testo: "And the client checks it alone." },
      { da: 71.514, testo: "One HTML page, offline, recomputes every fingerprint." },
      { da: 77.3, testo: "A report anyone can verify." },
    ],
  },
  de: {
    titolo: "EINE SCHICHT, VON ANFANG BIS ENDE",
    passi: "STEMPELN · ZWEI NACHWEISE · DER REPORT · DIE PRÜFUNG",
    nota: "Ein echtes Telefon und ein echter Bildschirm. Nichts ist nachgestellt.",
    atto: "AKT",
    atti: [
      "Die Schicht beginnt",
      "Der Schaden, fotografiert",
      "Er kommt von allein an",
      "Zwei Stunden später",
      "Die Schicht endet",
      "Der Auftrag wird geschlossen",
      "Geprüft ohne uns",
    ],
    chiusa: "Die Arbeit hinterlässt einen Beleg, den jeder prüfen kann — auch in Jahren, ohne uns zu fragen.",
    trascrizione: [
      { da: 0.3, testo: "Eine Schicht, wie sie lief." },
      { da: 3.3, testo: "Auf der Baustelle startet ein Tipp die Schicht." },
      { da: 6.018, testo: "Fünf Sekunden später zeigt der Bildschirm im Büro ihn schon bei der Arbeit." },
      { da: 10.356, testo: "Niemand hat etwas eingetippt." },
      { da: 13.3, testo: "Der Nachweis beginnt mit einem Foto." },
      { da: 15.489, testo: "Die Kamera öffnet sich in der App: keine Galerie, das Bild entsteht nur jetzt." },
      { da: 20.3, testo: "Zwei Sicherungen gefallen, Kabel aus dem Kanal." },
      { da: 23.286, testo: "Er schreibt, was er vorfindet, und schickt es ab." },
      { da: 28.3, testo: "Und da ist es, im Büro." },
      { da: 29.874, testo: "Diese Seite hat niemand angefasst." },
      { da: 33.3, testo: "Zwei Stunden später, derselbe Verteiler, instand gesetzt." },
      { da: 37.616, testo: "Zweites Foto." },
      { da: 39.3, testo: "Sicherungen wieder ein, Kabel im Kanal, Verteiler geprüft." },
      { da: 43.285, testo: "Gesendet, wie das erste." },
      { da: 46.3, testo: "Da sind die Nachweise." },
      { da: 47.807, testo: "Der zweite ist gerade angekommen." },
      { da: 50.3, testo: "Er stempelt aus: zwei Stunden dreiundfünfzig." },
      { da: 53.501, testo: "Im Büro stehen beide Buchungen auf Nachgewiesen." },
      { da: 56.915, testo: "Der Tag ist belegt." },
      { da: 60.3, testo: "Die Arbeit ist fertig." },
      { da: 61.655, testo: "Ein Knopf schließt den Auftrag und gibt den Bericht frei." },
      { da: 65.8, testo: "In einem ZIP." },
      { da: 66.829, testo: "Geschlossen und versiegelt." },
      { da: 69.3, testo: "Und der Kunde prüft ihn selbst." },
      { da: 71.576, testo: "Eine HTML-Seite, offline, rechnet jede Prüfsumme neu." },
      { da: 77.3, testo: "Ein Bericht, den jeder prüfen kann." },
    ],
  },
  fr: {
    titolo: "UNE JOURNÉE, DU DÉBUT À LA FIN",
    passi: "POINTAGE · DEUX PREUVES · LE RAPPORT · LA VÉRIFICATION",
    nota: "Un vrai téléphone et un vrai écran. Rien n’est reconstitué.",
    atto: "ACTE",
    atti: [
      "Le poste commence",
      "La panne, photographiée",
      "Elle arrive toute seule",
      "Deux heures plus tard",
      "Le poste se termine",
      "Le chantier est clôturé",
      "Vérifié sans nous",
    ],
    chiusa: "Le travail laisse un document que n’importe qui peut vérifier — même dans des années, sans nous le demander.",
    trascrizione: [
      { da: 0.3, testo: "Une journée, enregistrée pendant qu'elle se fait." },
      { da: 3.3, testo: "Sur le chantier, un geste ouvre la journée." },
      { da: 6.633, testo: "Cinq secondes plus tard, le bureau le voit déjà au travail." },
      { da: 11.206, testo: "Personne n'a rien saisi." },
      { da: 13.3, testo: "La preuve commence par une photo." },
      { da: 15.693, testo: "L'appareil s'ouvre dans l'app : pas de galerie." },
      { da: 20.3, testo: "Deux disjoncteurs déclenchés, des câbles hors de la goulotte." },
      { da: 24.451, testo: "Il écrit ce qu'il trouve et envoie." },
      { da: 28.3, testo: "Et là voilà, au bureau." },
      { da: 30.183, testo: "Cette page, personne n'y a touché." },
      { da: 33.3, testo: "Deux heures plus tard, le même tableau, remis en état." },
      { da: 37.787, testo: "Deuxième photo." },
      { da: 39.3, testo: "Disjoncteurs réarmés, câbles dans la goulotte, tableau refermé." },
      { da: 44.032, testo: "Envoyée." },
      { da: 46.3, testo: "Voilà les preuves." },
      { da: 48.084, testo: "La deuxième arrive." },
      { da: 50.3, testo: "Il pointe la sortie : deux heures cinquante-trois." },
      { da: 54.179, testo: "Les deux pointages affichent Prouvé." },
      { da: 56.972, testo: "La journée est couverte." },
      { da: 60.3, testo: "Le travail est fini." },
      { da: 61.909, testo: "Un bouton clôture et livre le rapport." },
      { da: 65.8, testo: "Dans un seul ZIP." },
      { da: 67.642, testo: "Clos et scellé." },
      { da: 69.3, testo: "Et le client le vérifie seul." },
      { da: 71.897, testo: "Une page HTML, hors ligne, recalcule chaque empreinte." },
      { da: 77.3, testo: "Un rapport que n'importe qui peut vérifier." },
    ],
  },
  es: {
    titolo: "UNA JORNADA, DE PRINCIPIO A FIN",
    passi: "FICHAJE · DOS PRUEBAS · EL INFORME · LA VERIFICACIÓN",
    nota: "Un teléfono real y una pantalla real. Nada está recreado.",
    atto: "ACTO",
    atti: [
      "Empieza la jornada",
      "La avería, fotografiada",
      "Llega sola",
      "Dos horas después",
      "Termina la jornada",
      "Se cierra el trabajo",
      "Verificado sin nosotros",
    ],
    chiusa: "El trabajo deja un documento que cualquiera puede verificar — dentro de años, sin pedírnoslo.",
    trascrizione: [
      { da: 0.3, testo: "Una jornada, registrada mientras ocurre." },
      { da: 3.3, testo: "En obra, un toque abre la jornada." },
      { da: 5.567, testo: "Cinco segundos después, la pantalla de la oficina ya lo muestra trabajando." },
      { da: 10.567, testo: "Nadie tocó nada." },
      { da: 13.3, testo: "La prueba empieza por una foto." },
      { da: 15.085, testo: "La cámara se abre en la app: sin galería, solo se puede hacer ahora." },
      { da: 20.3, testo: "Dos magnetotérmicos saltados, cables fuera de la canaleta." },
      { da: 23.94, testo: "Escribe lo que encuentra y lo envía." },
      { da: 28.3, testo: "Y ahí está, en la oficina." },
      { da: 30.322, testo: "Esa página no la tocó nadie." },
      { da: 33.3, testo: "Dos horas después, el mismo cuadro, arreglado." },
      { da: 36.497, testo: "Segunda foto." },
      { da: 39.3, testo: "Rearmados, cables en la canaleta, cuadro probado y cerrado." },
      { da: 42.999, testo: "Enviada, como la primera." },
      { da: 46.3, testo: "Ahí están las pruebas." },
      { da: 47.752, testo: "La segunda acaba de llegar." },
      { da: 50.3, testo: "Ficha la salida: dos horas y cincuenta y tres." },
      { da: 53.695, testo: "Los dos fichajes dicen Probado." },
      { da: 55.983, testo: "El día está cubierto." },
      { da: 60.3, testo: "El trabajo está hecho." },
      { da: 61.756, testo: "Un botón cierra el trabajo y entrega el informe." },
      { da: 65.8, testo: "En un solo ZIP." },
      { da: 67.088, testo: "Cerrado y sellado." },
      { da: 69.3, testo: "Y el cliente lo comprueba solo." },
      { da: 71.615, testo: "Una página HTML, offline, recalcula cada huella." },
      { da: 77.3, testo: "Un informe que cualquiera puede comprobar." },
    ],
  },
  nl: {
    titolo: "ÉÉN DIENST, VAN BEGIN TOT EIND",
    passi: "INKLOKKEN · TWEE BEWIJZEN · HET RAPPORT · DE CONTROLE",
    nota: "Een echte telefoon en een echt scherm. Niets is nagespeeld.",
    atto: "DEEL",
    atti: [
      "De dienst begint",
      "Het defect, gefotografeerd",
      "Het komt vanzelf binnen",
      "Twee uur later",
      "De dienst eindigt",
      "De opdracht wordt gesloten",
      "Gecontroleerd zonder ons",
    ],
    chiusa: "Het werk laat een document na dat iedereen kan controleren — over jaren nog, zonder het ons te vragen.",
    trascrizione: [
      { da: 0.3, testo: "Eén dienst, live vastgelegd." },
      { da: 3.3, testo: "Op de werf opent een tik de dienst." },
      { da: 6.287, testo: "Vijf seconden later ziet het kantoor hem al aan het werk." },
      { da: 11.152, testo: "Niemand raakte iets aan." },
      { da: 13.3, testo: "Het bewijs begint met een foto." },
      { da: 16.109, testo: "De camera opent in de app: geen galerij." },
      { da: 20.3, testo: "Twee automaten gesprongen, kabels uit de goot." },
      { da: 24.1, testo: "Hij schrijft op wat hij aantreft en verstuurt." },
      { da: 28.3, testo: "En daar is hij, op kantoor." },
      { da: 33.3, testo: "Twee uur later, dezelfde kast in orde." },
      { da: 37.328, testo: "Tweede foto." },
      { da: 39.3, testo: "Automaten terug in, kabels in de goot, kast gesloten." },
      { da: 44.544, testo: "Verstuurd." },
      { da: 46.3, testo: "De bewijzen." },
      { da: 47.656, testo: "De tweede is net binnen." },
      { da: 50.3, testo: "Hij klokt uit: twee uur drieënvijftig." },
      { da: 54.114, testo: "Beide boekingen staan op Bewezen." },
      { da: 57.427, testo: "De dag is gedekt." },
      { da: 60.3, testo: "Het werk is klaar." },
      { da: 61.91, testo: "Eén knop sluit de klus en levert het rapport." },
      { da: 65.8, testo: "In één ZIP, verzegeld." },
      { da: 69.3, testo: "De klant controleert het zelf." },
      { da: 72.114, testo: "Eén HTML-pagina, offline, herberekent elke vingerafdruk." },
      { da: 77.3, testo: "Een rapport dat iedereen kan controleren." },
    ],
  },
  pt: {
    titolo: "UM TURNO, DO INÍCIO AO FIM",
    passi: "PICAGEM · DUAS PROVAS · O RELATÓRIO · A VERIFICAÇÃO",
    nota: "Um telefone real e um ecrã real. Nada é recriado.",
    atto: "ATO",
    atti: [
      "O turno começa",
      "A avaria, fotografada",
      "Chega sozinha",
      "Duas horas depois",
      "O turno termina",
      "A obra é fechada",
      "Verificado sem nós",
    ],
    chiusa: "O trabalho deixa um documento que qualquer pessoa pode verificar — daqui a anos, sem nos pedir nada.",
    trascrizione: [
      { da: 0.3, testo: "Um turno, gravado ao vivo." },
      { da: 3.3, testo: "Na obra, um toque abre o turno." },
      { da: 5.042, testo: "Cinco segundos depois, o ecrã do escritório já o mostra a trabalhar." },
      { da: 8.864, testo: "Ninguém tocou em nada." },
      { da: 13.3, testo: "A prova começa com uma foto." },
      { da: 15.139, testo: "A câmara abre na aplicação: sem galeria." },
      { da: 20.3, testo: "Dois disjuntores disparados, cabos fora da calha." },
      { da: 23.184, testo: "Escreve o que encontrou e envia." },
      { da: 28.3, testo: "E ali está, no escritório." },
      { da: 29.923, testo: "Ninguém tocou naquela página." },
      { da: 33.3, testo: "Duas horas depois, o mesmo quadro, reposto." },
      { da: 35.972, testo: "Segunda foto, tirada da mesma maneira." },
      { da: 39.3, testo: "Disjuntores rearmados, cabos na calha, quadro fechado." },
      { da: 42.672, testo: "Enviada, como a primeira." },
      { da: 46.3, testo: "Ali estão as provas." },
      { da: 47.548, testo: "A segunda acabou de chegar." },
      { da: 50.3, testo: "Pica a saída: duas horas e cinquenta e três." },
      { da: 53.265, testo: "As duas picagens dizem Provado." },
      { da: 55.353, testo: "O dia está coberto." },
      { da: 60.3, testo: "O trabalho está feito." },
      { da: 61.5, testo: "Um botão fecha a obra e entrega o relatório." },
      { da: 65.8, testo: "Num único ZIP." },
      { da: 66.809, testo: "Fechado e selado." },
      { da: 69.3, testo: "E o cliente verifica sozinho." },
      { da: 71.209, testo: "Uma página HTML, offline, recalcula cada impressão." },
      { da: 77.3, testo: "Um relatório que qualquer um pode verificar." },
    ],
  },
  da: {
    titolo: "EN VAGT, FRA START TIL SLUT",
    passi: "STEMPLING · TO BEVISER · RAPPORTEN · KONTROLLEN",
    nota: "En rigtig telefon og en rigtig skærm. Intet er iscenesat.",
    atto: "AKT",
    atti: [
      "Vagten begynder",
      "Fejlen, fotograferet",
      "Den kommer af sig selv",
      "To timer senere",
      "Vagten slutter",
      "Opgaven lukkes",
      "Kontrolleret uden os",
    ],
    chiusa: "Arbejdet efterlader et dokument, som enhver kan kontrollere — også om mange år, uden at spørge os.",
    trascrizione: [
      { da: 0.3, testo: "Én vagt, optaget live." },
      { da: 3.3, testo: "På pladsen åbner ét tryk vagten." },
      { da: 5.514, testo: "Fem sekunder senere viser skærmen på kontoret ham allerede i arbejde." },
      { da: 10.288, testo: "Ingen rørte noget." },
      { da: 13.3, testo: "Beviset begynder med et foto." },
      { da: 15.408, testo: "Kameraet åbner inde i appen: intet galleri." },
      { da: 20.3, testo: "To sikringer slået fra, kabler ude af kanalen." },
      { da: 23.135, testo: "Han skriver, hvad han finder, og sender." },
      { da: 28.3, testo: "Og der er det, på kontoret." },
      { da: 30.047, testo: "Den side har ingen rørt." },
      { da: 33.3, testo: "To timer senere, samme tavle, sat i stand." },
      { da: 36.866, testo: "Andet foto." },
      { da: 39.3, testo: "Sikringer slået til, kabler i kanalen, tavlen lukket." },
      { da: 42.998, testo: "Sendt, som den første." },
      { da: 46.3, testo: "Der er beviserne." },
      { da: 47.46, testo: "Det andet er lige landet." },
      { da: 50.3, testo: "Han stempler ud: to timer og treoghalvtreds." },
      { da: 53.722, testo: "Begge stemplinger står på Bevist." },
      { da: 56.289, testo: "Dagen er dækket." },
      { da: 60.3, testo: "Arbejdet er færdigt." },
      { da: 61.795, testo: "Én knap lukker opgaven og udleverer rapporten." },
      { da: 65.8, testo: "I én ZIP." },
      { da: 66.597, testo: "Lukket og forseglet." },
      { da: 69.3, testo: "Og kunden tjekker den selv." },
      { da: 71.367, testo: "Én HTML-side, offline, genberegner hvert fingeraftryk." },
      { da: 77.3, testo: "En rapport, som enhver kan tjekke." },
    ],
  },
  sv: {
    titolo: "ETT SKIFT, FRÅN BÖRJAN TILL SLUT",
    passi: "STÄMPLING · TVÅ BEVIS · RAPPORTEN · KONTROLLEN",
    nota: "En riktig telefon och en riktig skärm. Inget är iscensatt.",
    atto: "AKT",
    atti: [
      "Skiftet börjar",
      "Felet, fotograferat",
      "Det kommer in av sig självt",
      "Två timmar senare",
      "Skiftet slutar",
      "Uppdraget stängs",
      "Kontrollerat utan oss",
    ],
    chiusa: "Arbetet lämnar ett dokument som vem som helst kan kontrollera — om flera år, utan att fråga oss.",
    trascrizione: [
      { da: 0.3, testo: "Ett arbetspass, inspelat live." },
      { da: 3.3, testo: "På plats öppnar en tryckning passet." },
      { da: 6.556, testo: "Fem sekunder senare ser kontoret honom redan i arbete." },
      { da: 11.439, testo: "Ingen rörde något." },
      { da: 13.3, testo: "Beviset börjar med ett foto." },
      { da: 15.469, testo: "Kameran öppnas inne i appen: inget galleri." },
      { da: 20.3, testo: "Två automatsäkringar utlösta, kablar ute ur kanalen." },
      { da: 24.814, testo: "Han skriver vad han hittar och skickar." },
      { da: 28.3, testo: "Och där är det, på kontoret." },
      { da: 30.66, testo: "Den sidan har ingen rört." },
      { da: 33.3, testo: "Två timmar senare, samma central, åtgärdad." },
      { da: 37.392, testo: "Andra fotot." },
      { da: 39.3, testo: "Säkringar återställda, kablar i kanalen, centralen stängd." },
      { da: 44.895, testo: "Skickat." },
      { da: 46.3, testo: "Där är bevisen." },
      { da: 48.05, testo: "Det andra kom just." },
      { da: 50.3, testo: "Han stämplar ut: två timmar och femtiotre." },
      { da: 54.135, testo: "Båda stämplingarna står på Bevisad." },
      { da: 57.33, testo: "Dagen är täckt." },
      { da: 60.3, testo: "Jobbet är klart." },
      { da: 61.608, testo: "En knapp stänger jobbet och lämnar ut rapporten." },
      { da: 65.8, testo: "I en enda ZIP, stängd och förseglad." },
      { da: 69.3, testo: "Och kunden kontrollerar den själv." },
      { da: 72.532, testo: "En HTML-sida, offline, räknar om varje avtryck." },
      { da: 77.3, testo: "En rapport vem som helst kan kontrollera." },
    ],
  },
  nb: {
    titolo: "ETT SKIFT, FRA START TIL SLUTT",
    passi: "STEMPLING · TO BEVIS · RAPPORTEN · KONTROLLEN",
    nota: "En ekte telefon og en ekte skjerm. Ingenting er iscenesatt.",
    atto: "AKT",
    atti: [
      "Skiftet starter",
      "Feilen, fotografert",
      "Den kommer av seg selv",
      "To timer senere",
      "Skiftet slutter",
      "Oppdraget lukkes",
      "Kontrollert uten oss",
    ],
    chiusa: "Arbeidet etterlater et dokument som hvem som helst kan kontrollere — om mange år, uten å spørre oss.",
    trascrizione: [
      { da: 0.3, testo: "Ett skift, tatt opp live." },
      { da: 3.3, testo: "På anlegget åpner ett trykk skiftet." },
      { da: 5.432, testo: "Fem sekunder senere viser skjermen på kontoret ham allerede i arbeid." },
      { da: 9.519, testo: "Ingen rørte noe." },
      { da: 13.3, testo: "Beviset starter med et bilde." },
      { da: 15.206, testo: "Kameraet åpnes inne i appen: ingen galleri." },
      { da: 20.3, testo: "To sikringer slått ut, kabler ute av kanalen." },
      { da: 22.957, testo: "Han skriver det han finner, og sender." },
      { da: 28.3, testo: "Og der er det, på kontoret." },
      { da: 29.996, testo: "Den siden har ingen rørt." },
      { da: 33.3, testo: "To timer senere, samme tavle, satt i stand." },
      { da: 36.271, testo: "Andre bilde." },
      { da: 39.3, testo: "Sikringer tilbake på, kabler i kanalen, tavlen lukket." },
      { da: 42.829, testo: "Sendt, som det første." },
      { da: 46.3, testo: "Der er bevisene." },
      { da: 47.409, testo: "Det andre kom nettopp." },
      { da: 50.3, testo: "Han stempler ut: to timer og femtitre." },
      { da: 52.992, testo: "Begge stemplingene står på Bevist." },
      { da: 55.4, testo: "Dagen er dekket." },
      { da: 60.3, testo: "Jobben er ferdig." },
      { da: 61.316, testo: "Én knapp lukker oppdraget og frigir rapporten." },
      { da: 65.8, testo: "I én ZIP." },
      { da: 66.669, testo: "Lukket og forseglet." },
      { da: 69.3, testo: "Og kunden sjekker den selv." },
      { da: 71.122, testo: "Én HTML-side, offline, regner ut hvert avtrykk på nytt." },
      { da: 77.3, testo: "En rapport hvem som helst kan sjekke." },
    ],
  },
  ru: {
    titolo: "ОДНА СМЕНА, ОТ НАЧАЛА ДО КОНЦА",
    passi: "ОТМЕТКА · ДВА ПОДТВЕРЖДЕНИЯ · ОТЧЁТ · ПРОВЕРКА",
    nota: "Настоящий телефон и настоящий экран. Ничего не воссоздано.",
    atto: "ДЕЙСТВИЕ",
    atti: [
      "Смена начинается",
      "Неисправность, сфотографирована",
      "Приходит сама",
      "Через два часа",
      "Смена заканчивается",
      "Заказ закрывается",
      "Проверено без нас",
    ],
    chiusa: "Работа оставляет документ, который может проверить любой — хоть через годы, не спрашивая нас.",
    trascrizione: [
      { da: 0.3, testo: "Одна смена, записанная вживую." },
      { da: 3.3, testo: "На объекте одно касание открывает смену." },
      { da: 6.311, testo: "Через пять секунд экран в офисе уже показывает его на работе." },
      { da: 10.902, testo: "Никто ничего не вводил." },
      { da: 13.3, testo: "Доказательство начинается с фото." },
      { da: 15.739, testo: "Камера открывается внутри приложения: галереи нет." },
      { da: 20.3, testo: "Два автомата выбило, кабели вне короба." },
      { da: 23.488, testo: "Он пишет, что нашёл, и отправляет." },
      { da: 28.3, testo: "И вот оно, в офисе." },
      { da: 29.976, testo: "Эту страницу никто не трогал." },
      { da: 33.3, testo: "Через два часа тот же щит, приведён в порядок." },
      { da: 36.816, testo: "Второе фото." },
      { da: 39.3, testo: "Автоматы взведены, кабели в коробе, щит закрыт." },
      { da: 42.847, testo: "Отправлено, как и первое." },
      { da: 46.3, testo: "Вот доказательства." },
      { da: 47.84, testo: "Второе только что пришло." },
      { da: 50.3, testo: "Он отмечает уход: два часа пятьдесят три." },
      { da: 53.887, testo: "Обе отметки — Подтверждено." },
      { da: 56.25, testo: "День закрыт." },
      { da: 60.3, testo: "Работа закончена." },
      { da: 61.754, testo: "Одна кнопка закрывает заказ и выдаёт отчёт." },
      { da: 65.8, testo: "В одном ZIP." },
      { da: 67.213, testo: "Закрыт и опечатан." },
      { da: 69.3, testo: "И клиент проверяет сам." },
      { da: 71.24, testo: "Одна HTML-страница, офлайн, заново считает каждый отпечаток." },
      { da: 77.3, testo: "Отчёт, который может проверить любой." },
    ],
  },
};
