<?php
/**
 * Child theme functions.
 * Generated by WP Agent.
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * Enqueue parent and child theme styles.
 */
add_action( 'wp_enqueue_scripts', function () {
    // Parent theme style
    wp_enqueue_style(
        'parent-style',
        get_template_directory_uri() . '/style.css'
    );

    // Child theme style (dipende dal parent)
    wp_enqueue_style(
        'child-style',
        get_stylesheet_uri(),
        array( 'parent-style' ),
        wp_get_theme()->get( 'Version' )
    );

    // CSS aggiuntivo
    $custom_css = get_stylesheet_directory() . '/custom.css';
    if ( file_exists( $custom_css ) ) {
        wp_enqueue_style(
            'child-theme-custom',
            get_stylesheet_directory_uri() . '/custom.css',
            array( 'child-style' ),
            filemtime( $custom_css )
        );
    }
} );

// Fix: force GD first for image processing (Imagick 6.9/aarch64 bug with large PNG)
add_filter( 'wp_image_editors', function( $editors ) {
    return array( 'WP_Image_Editor_GD', 'WP_Image_Editor_Imagick' );
} );

// Raise big image threshold to 4000px to avoid spurious scaling failures
add_filter( 'big_image_size_threshold', function() {
    return 4000;
} );

// Fix: Application Passwords behind Cloudflare proxy
add_filter( 'determine_current_user', function( $user ) {
    if ( ! isset( $_SERVER['HTTP_AUTHORIZATION'] ) ) {
        if ( isset( $_SERVER['REDIRECT_HTTP_AUTHORIZATION'] ) ) {
            $_SERVER['HTTP_AUTHORIZATION'] = $_SERVER['REDIRECT_HTTP_AUTHORIZATION'];
        } elseif ( isset( $_SERVER['HTTP_X_HTTP_AUTHORIZATION'] ) ) {
            $_SERVER['HTTP_AUTHORIZATION'] = $_SERVER['HTTP_X_HTTP_AUTHORIZATION'];
        } elseif ( function_exists( 'apache_request_headers' ) ) {
            $headers = apache_request_headers();
            if ( isset( $headers['Authorization'] ) ) {
                $_SERVER['HTTP_AUTHORIZATION'] = $headers['Authorization'];
            }
        }
    }
    return $user;
}, 9 );



/* === Category filter + reading time — Design Refresh 2026-03-28 === */
add_action( 'loop_start', function () {
    if ( ! is_home() && ! is_archive() ) return;
    $categories = get_categories( array( 'hide_empty' => true, 'orderby' => 'count', 'order' => 'DESC' ) );
    if ( empty( $categories ) ) return;
    echo '<div class="gt-category-filter" id="gt-cat-filter">';
    echo '<button class="active" data-cat="all">Tutti</button>';
    foreach ( $categories as $cat ) {
        echo '<button data-cat="' . esc_attr( $cat->slug ) . '">' . esc_html( $cat->name ) . '</button>';
    }
    echo '</div>';
    echo '<script>(function(){var f=document.getElementById("gt-cat-filter");if(!f)return;f.addEventListener("click",function(e){if(e.target.tagName!=="BUTTON")return;var cat=e.target.dataset.cat;f.querySelectorAll("button").forEach(function(b){b.classList.remove("active");});e.target.classList.add("active");document.querySelectorAll("article.group").forEach(function(el){if(cat==="all"){el.style.display="";return;}var cats=(el.dataset.cats||"").split(",");el.style.display=(cats.indexOf(cat)>-1)?"":"none";});});})()</script>';
} );

add_action( 'wp_footer', function () {
    if ( ! is_home() && ! is_archive() ) return;
    $posts = get_posts(array('posts_per_page' => -1, 'post_status' => 'publish'));
    $map = array();
    foreach ($posts as $p) {
        $cats = get_the_category($p->ID);
        $slugs = array_map(function($c){ return $c->slug; }, $cats);
        $map['post-' . $p->ID] = implode(',', $slugs);
    }
    echo '<script>(function(){var m=' . json_encode($map) . ';Object.keys(m).forEach(function(id){var el=document.getElementById(id);if(el)el.dataset.cats=m[id];});})()</script>';
} );

add_filter( 'the_excerpt', function( $excerpt ) {
    if ( ! in_the_loop() || ! is_main_query() ) return $excerpt;
    $wc = str_word_count( strip_tags( get_the_content() ) );
    $min = max( 1, (int) ceil( $wc / 200 ) );
    return '<span class="card-reading-time">&#9201; ' . $min . ' min</span>' . $excerpt;
} );
