import type { VerifierCopy } from './types';

const en: VerifierCopy = {
  hero_badge: 'GeoTapp Verifier — Work Report Verification',
  hero_title: 'Your work reports\nare verifiable.',
  hero_subtitle:
    'GeoTapp Verifier checks that an intervention report matches the operational data recorded in the field and has not been modified. More credibility for the client, fewer disputes.',
  hero_cta_primary: 'Request a Demo',
  hero_cta_secondary: 'See how it works',
  terminal_integrity: 'Document integrity: VERIFIED',
  terminal_timestamps: 'Timestamp match: CONFIRMED',
  terminal_gps: 'GPS coordinates: CONSISTENT',
  terminal_not_modified: 'Document not modified: CONFIRMED',
  terminal_operator: 'Operator verified: OK',
  terminal_summary_title: 'Verification Summary',
  terminal_technician_label: 'Technician:',
  terminal_date_label: 'Intervention date:',
  terminal_site_label: 'Site:',
  terminal_verified_line: 'REPORT AUTHENTIC AND INTACT',
  ecosystem_timetracker_desc:
    'Collects operational data in the field: GPS timestamps, photos, notes and client signature.',
  ecosystem_timetracker_link: 'Explore TimeTracker',
  ecosystem_flow_desc:
    'Organises jobs, teams and generates structured reports with cryptographic identifier.',
  ecosystem_flow_link: 'Explore Flow',
  ecosystem_verifier_desc:
    'Verifies the integrity of every report. Cross-checks the document against the original data and certifies authenticity.',
  problem_badge: 'The real problem',
  problem_title: 'An unverifiable report is a contestable report.',
  problem_items: [
    {
      title: 'Clients questioning work performed',
      desc: 'Without independent proof, any report can be disputed. The client does not know whether what is written matches what was actually done.',
    },
    {
      title: 'Timesheets that are hard to defend',
      desc: 'Manual signatures and paper timesheets are not enough. When a dispute arises about hours or on-site presence, the document alone does not convince.',
    },
    {
      title: 'Reports that can be edited after the fact',
      desc: 'A document that can be modified after delivery offers no real guarantees. Clients know this, and it creates distrust even when the work was performed perfectly.',
    },
  ],
  what_badge: 'What GeoTapp Verifier is',
  what_title: 'Independent verification of intervention reports.',
  what_desc:
    'GeoTapp Verifier is the system that allows you to verify the authenticity and integrity of reports generated by GeoTapp Flow and TimeTracker. It cross-checks the document against the original operational data — GPS timestamps, locations, photo evidence — and certifies that the report has not been altered.',
  how_badge: 'How it works',
  how_title: 'Three steps. One verified report.',
  how_steps: [
    {
      num: '01',
      title: 'The technician records field activity',
      desc: 'With GeoTapp TimeTracker, every intervention generates operational data: GPS timestamps, photos, notes and client signature. Data syncs to GeoTapp Flow in real time.',
    },
    {
      num: '02',
      title: 'Flow generates the structured report',
      desc: 'GeoTapp Flow collects all job data and produces a structured work report. The report includes a cryptographic identifier that links the document to the original data.',
    },
    {
      num: '03',
      title: 'Verifier checks integrity',
      desc: 'Anyone can verify the report with GeoTapp Verifier. The system cross-checks the document against the recorded operational data and certifies whether the report is intact and authentic.',
    },
  ],
  features_badge: 'What it verifies',
  features_title: 'Every aspect of the report is checkable.',
  features: [
    {
      title: 'Hours and durations',
      desc: 'Verifies that reported hours match GPS timestamps recorded by TimeTracker on the field.',
    },
    {
      title: 'Locations and sites',
      desc: 'Checks that coordinates and addresses in the report match the GPS data captured during the intervention.',
    },
    {
      title: 'Document integrity',
      desc: 'Certifies that the document has not been modified after generation. Any alteration is detected.',
    },
    {
      title: 'Data authenticity',
      desc: 'Verifies that the operational data in the report comes from GeoTapp systems and has not been entered manually.',
    },
    {
      title: 'Operators and assignments',
      desc: 'Checks that the technicians listed in the report are the same ones who recorded field activity.',
    },
    {
      title: 'Verifiable without platform access',
      desc: 'The client can verify the report independently, without needing to access the GeoTapp platform.',
    },
  ],
  who_badge: 'Who it is for',
  who_title: 'For companies that need to defend their work.',
  who_items: [
    'Maintenance and technical assistance companies',
    'Cleaning and facility management companies',
    'Security and surveillance services',
    'Installation teams and field crews',
    'Any company that needs to prove on-site presence and field activity',
  ],
  ecosystem_badge: 'GeoTapp Ecosystem',
  ecosystem_title: 'Verifier works with Flow and TimeTracker.',
  ecosystem_desc:
    'GeoTapp Verifier is not a standalone tool. It is the final step of an integrated operational cycle: data is collected in the field with TimeTracker, organised in Flow, and then certified by Verifier.',
  cta_title: 'Start producing verifiable reports.',
  cta_subtitle:
    'Discover how GeoTapp Verifier can help your company reduce disputes and increase credibility with clients.',
  cta_primary: 'Request a Demo',
  cta_flow: 'Explore GeoTapp Flow',
  cta_timetracker: 'Explore GeoTapp TimeTracker',
  faq_badge: 'Frequently asked questions',
  faq_title: 'Everything you want to know about Verifier.',
  faqs: [
    {
      q: 'Does the client need a GeoTapp account to verify a report?',
      a: 'No. GeoTapp Verifier is designed for independent verification. The client receives the report and can verify its authenticity without registering or accessing the platform.',
    },
    {
      q: 'What happens if someone tries to modify the report?',
      a: 'Any modification to the document after generation is detected by Verifier. The system cross-checks the report against the original operational data and immediately flags any discrepancy.',
    },
    {
      q: 'Does Verifier work for historical reports?',
      a: 'Yes. All reports generated by GeoTapp Flow with TimeTracker data can be verified at any time, even months or years after they were produced.',
    },
    {
      q: 'Does Verifier need to be purchased separately?',
      a: 'GeoTapp Verifier is integrated into the GeoTapp ecosystem. Contact us to understand which plan best suits your company needs.',
    },
  ],
  hero_cta_download: 'Download free — v0.1.0',
  cta_download: 'Download Verifier free',
  download_badge: 'Free download',
  download_title: 'Download GeoTapp Verifier.',
  download_desc: 'Open CLI tool to verify GeoTapp report integrity offline. No account required. Works from terminal or as a Node.js library.',
  download_btn: 'Download report-verifier-0.1.0.zip',
  download_version: 'v0.1.0 — ~40 KB — Requires Node.js ≥ 18',
  download_requirements: 'Requires Node.js ≥ 18',
  download_cli_title: 'From terminal',
  download_api_title: 'As Node.js library',

  online_verify_badge: 'Instant verification',
  online_verify_title: 'Verify a report online',
  online_verify_desc: 'Upload the report ZIP file. Verification happens on the server and the file is not stored.',
  online_verify_upload_label: 'Drag the report ZIP here, or click to select',
  online_verify_upload_hint: '.zip files only — max 25MB',
  online_verify_btn: 'Verify now',
  online_verify_privacy_note: 'The file is processed in memory and never stored or shared with third parties.',
  online_verify_size_limit: 'Maximum size: 25MB',
  online_verify_result_valid_sealed: 'Valid report — sealed and signed',
  online_verify_result_valid_unsigned: 'Valid report — content intact, seal not cryptographically signed',
  online_verify_result_legacy: 'Legacy report — readable, no strong seal',
  online_verify_result_invalid: 'Invalid report — content may have been altered',
  online_verify_error_too_large: 'File too large. Maximum size: 25MB.',
  online_verify_error_not_zip: 'File must be a ZIP archive.',
  online_verify_error_generic: 'Verification error. The file may be corrupted.',
  compare_badge: 'Two ways to verify',
  compare_title: 'Local or online verification?',
  compare_local_title: 'Local (CLI / SDK)',
  compare_local_items: [
    'File stays on your device',
    'Works without internet connection',
    'No practical size limit',
    'Ideal for audits, legal, consultants',
    'Requires Node.js installed',
  ],
  compare_online_title: 'Online (this site)',
  compare_online_items: [
    'No tool to install',
    'Instant result in the browser',
    'File passes through the server (disclosed)',
    '25MB file size limit',
    'Ideal for quick checks',
  ],
  compare_same_engine_note: 'Same verification engine in both cases. The difference is where it runs.',
};

export default en;
