import type { VerifierCopy } from './types';

const en: VerifierCopy = {
  hero_badge: 'GeoTapp Verifier - Work Report Verification',
  hero_title: 'Your work reports\nare verifiable.',
  hero_subtitle:
    'GeoTapp Verifier checks that a GeoTapp report has not been modified since it was sealed, and that it really was GeoTapp that issued it. It is free, for you and for your clients, and it works offline too.',
  hero_cta_primary: 'Try GeoTapp free',
  hero_cta_secondary: 'See how it works',
  terminal_integrity: 'Event chain: INTACT',
  terminal_timestamps: 'Seal time: FROM THE SERVER',
  terminal_gps: 'Photo fingerprints: MATCHING',
  terminal_not_modified: 'Document not modified: CONFIRMED',
  terminal_operator: 'GeoTapp signature: VALID',
  terminal_summary_title: 'Verification Summary',
  terminal_technician_label: 'Technician:',
  terminal_date_label: 'Intervention date:',
  terminal_site_label: 'Site:',
  terminal_verified_line: 'DOCUMENT INTACT AND SIGNED',
  ecosystem_timetracker_desc:
    'Collects field data: clock-ins with position and time, proof photos and notes.',
  ecosystem_timetracker_link: 'Explore TimeTracker',
  ecosystem_flow_desc:
    'Organises jobs and teams and generates structured, sealed reports, ready to be verified.',
  ecosystem_flow_link: 'Explore Flow',
  ecosystem_verifier_desc:
    'Verifies the integrity of every report: it recomputes the fingerprints and checks the GeoTapp signature.',
  problem_badge: 'The real problem',
  problem_title: 'An unverifiable report is a contestable report.',
  problem_items: [
    {
      title: 'Clients questioning work performed',
      desc: 'Without independent proof, any report can be questioned. The client does not know whether what is written matches what was actually done.',
    },
    {
      title: 'Hours and attendance that are hard to defend',
      desc: 'Sign-in sheets and manual clock-ins are not enough. When a dispute arises about hours or on-site presence, the document alone does not convince.',
    },
    {
      title: 'Reports that are edited or incomplete',
      desc: 'A document that can be modified after the fact without leaving a trace cannot be verified. Clients know this, and it creates distrust even when the work was performed perfectly.',
    },
  ],
  what_badge: 'What GeoTapp Verifier is',
  what_title: 'Independent verification of intervention reports.',
  what_desc:
    'GeoTapp Verifier lets anyone check a report generated by GeoTapp Flow and TimeTracker: it recomputes the fingerprints of the clock-ins, positions and photos contained in the package, and verifies the GeoTapp signature. It tells you whether the document is intact and where it comes from; on its own it does not prove that the event took place, nor is it legal advice.',
  how_badge: 'How it works',
  how_title: 'Three steps. One verified report.',
  how_steps: [
    {
      num: '01',
      title: 'The technician records field activity',
      desc: 'With GeoTapp TimeTracker every intervention generates data: clock-ins with position and time, proof photos and notes. The data reaches GeoTapp Flow as soon as the phone has a connection.',
    },
    {
      num: '02',
      title: 'Flow generates the structured report',
      desc: 'GeoTapp Flow collects the job data and produces the report. The report is then sealed: from that moment any modification can be detected.',
    },
    {
      num: '03',
      title: 'Verifier checks integrity',
      desc: 'Anyone can verify the report with GeoTapp Verifier: it recomputes the fingerprints, checks the signature and tells you whether the report is intact and whether it comes from GeoTapp.',
    },
  ],
  features_badge: 'What it verifies',
  features_title: 'Every aspect of the report is checkable.',
  features: [
    {
      title: 'Event chain',
      desc: 'Each clock-in is linked to the previous one by a SHA-256 fingerprint: if an event is removed, added or changed, the chain breaks.',
    },
    {
      title: 'Proof photos',
      desc: 'The fingerprint of every photo is in the package: changing a single pixel is enough for it to stop matching.',
    },
    {
      title: 'Document integrity',
      desc: 'Verifies that the document has not been modified after generation. Any alteration is detected.',
    },
    {
      title: 'GeoTapp signature',
      desc: 'The root of the package is signed with the GeoTapp key: the check tells you whether it was really us who issued it.',
    },
    {
      title: 'Seal time',
      desc: 'The seal time comes from the server clock, not from the phone.',
    },
    {
      title: 'Verifiable without platform access',
      desc: 'The client can verify the report independently, without needing to access the GeoTapp platform, even offline.',
    },
  ],
  who_badge: 'Who it is for',
  who_title: 'For companies that need to prove their work.',
  who_items: [
    'Maintenance and technical assistance companies',
    'Cleaning and facility management companies',
    'Security and surveillance services',
    'Installation teams and field crews',
    'Any company that needs to prove on-site presence and field activity',
  ],
  ecosystem_badge: 'GeoTapp Ecosystem',
  ecosystem_title: 'Verifier works with Flow and TimeTracker.',
  ecosystem_desc:
    'GeoTapp Verifier is not a standalone tool. It is the final step of an integrated operational cycle: data is collected in the field with TimeTracker, organised in Flow, and then verified by Verifier.',
  cta_title: 'Start producing verifiable reports.',
  cta_subtitle:
    'With reports the client can verify alone, when someone disputes the work you have proof to show instead of one word against another.',
  cta_primary: 'Try GeoTapp free',
  cta_flow: 'Explore GeoTapp Flow',
  cta_timetracker: 'Explore GeoTapp TimeTracker',
  faq_badge: 'Frequently asked questions',
  faq_title: 'Everything you want to know about Verifier.',
  faqs: [
    {
      q: 'Does the client need a GeoTapp account to verify a report?',
      a: 'No. The client receives the report and verifies it without registering and without accessing the platform: online, or with the free offline verifier.',
    },
    {
      q: 'What happens if someone tries to modify the report?',
      a: 'The verifier recomputes the fingerprints of events and photos: any modification after generation makes them differ from the sealed ones, and the check flags the document as altered.',
    },
    {
      q: 'Does Verifier work for historical reports?',
      a: 'Yes. All reports generated by GeoTapp Flow with TimeTracker data can be verified at any time, even months or years after they were produced.',
    },
    {
      q: 'Is Verifier paid?',
      a: 'No, it is free: for you and for anyone who receives one of your reports.',
    },
  ],
  hero_cta_download: 'Download the verifier',
  cta_download: 'Download Verifier free',
  download_badge: 'Free download',
  download_title: 'Download GeoTapp Verifier.',
  download_desc: "Verify GeoTapp report integrity offline. No account required: from terminal or Node.js library if you're a developer, or a single HTML file that opens with a double-click for everyone else.",
  download_btn_cli: 'Download for command line (Node.js)',
  download_btn_html: 'Download the local HTML version',
  download_version: 'v0.3.0 · same verification engine, two formats',
  download_requirements: 'Requires Node.js ≥ 18',
  download_cli_title: 'From terminal',
  download_api_title: 'As Node.js library',

  online_verify_badge: 'Instant verification',
  online_verify_title: 'Verify a report online',
  online_verify_desc: 'Upload the report ZIP file. Verification happens on the server and the file is not stored.',
  online_verify_upload_label: 'Drag the report ZIP here, or click to select',
  online_verify_upload_hint: '.zip files only, max 25MB',
  online_verify_btn: 'Verify now',
  online_verify_privacy_note: 'The file is processed in memory and never stored or shared with third parties.',
  online_verify_size_limit: 'Maximum size: 25MB',
  online_verify_result_valid_sealed: 'Valid report, sealed and signed',
  online_verify_result_valid_unsigned: 'Valid report, content intact, seal not cryptographically signed',
  online_verify_result_legacy: 'Legacy report, readable, no strong seal',
  online_verify_result_invalid: 'Invalid report, content may have been altered',
  online_verify_error_too_large: 'File too large. Maximum size: 25MB.',
  online_verify_error_not_zip: 'File must be a ZIP archive.',
  online_verify_error_generic: 'Verification error. The file may be corrupted.',
  compare_badge: 'Two ways to verify',
  compare_title: 'Local or online verification?',
  compare_local_title: 'On your computer',
  compare_local_items: [
    'File stays on your device',
    'Works without internet connection',
    'No practical size limit',
    'Ideal for audits, lawyers, consultants',
    'The HTML version needs no installation; the command-line one requires Node.js',
  ],
  compare_online_title: 'Online (this site)',
  compare_online_items: [
    'No tool to install',
    'Instant result in the browser',
    'The file passes through our server, which does not store it',
    '25MB file size limit',
    'Ideal for quick checks',
  ],
  compare_same_engine_note: 'Same verification engine in both cases. The difference is where it runs.',
};

export default en;
