/**
 * Competitor comparison data, used by /confronto/dinamico/ DynamicComparison.tsx.
 *
 * 12 features in fixed order (matches the static `/confronto/geotapp-vs-{competitor}/`
 * pages already published, to preserve consistency).
 *
 * For each competitor we store: id, label, marketing site URL (so the user can
 * verify), pricing tier (rough EUR/seat/month for entry plan), and a 12-bool
 * vector aligned to FEATURE_KEYS. GeoTapp's vector is fixed (defined once).
 */

export type LocalizedString = Partial<Record<
  'it' | 'en' | 'de' | 'fr' | 'es' | 'nl' | 'pt' | 'da' | 'sv' | 'nb' | 'ru',
  string
>>;

/** 12 feature keys in the canonical order used by all comparison tables. */
export const FEATURE_KEYS = [
  'gps_verified_at_site',
  'sealed_report',
  'geo_timestamped_photos',
  'client_verification',
  'time_tracking',
  'mobile_app',
  'builtin_messaging',
  'payroll_export',
  'free_plan',
  'multi_site_jobs',
  'gdpr_geo_compliance',
  'auto_gps_notice_signed',
] as const;

export type FeatureKey = typeof FEATURE_KEYS[number];

export const FEATURE_LABELS: Record<FeatureKey, LocalizedString> = {
  gps_verified_at_site: {
    it: 'Posizione controllata a ogni timbratura',
    en: 'Position checked at every clock-in',
    de: 'Standort bei jeder Stempelung geprüft',
    fr: 'Position contrôlée à chaque pointage',
    es: 'GPS verificado en el sitio de trabajo',
    nl: 'Locatie gecontroleerd bij elke registratie',
    pt: 'GPS verificado no local de trabalho',
    da: 'GPS verificeret på arbejdsstedet',
    sv: 'GPS-verifierad på arbetsplatsen',
    nb: 'GPS-verifisert på arbeidsstedet',
    ru: 'GPS-проверка на месте работ',
  },
  sealed_report: {
    it: 'Report sigillato crittograficamente',
    en: 'Cryptographically sealed report',
    de: 'Kryptografisch versiegelter Bericht',
    fr: 'Rapport scellé cryptographiquement',
    es: 'Informe sellado criptográficamente',
    nl: 'Cryptografisch verzegeld rapport',
    pt: 'Relatório selado criptograficamente',
    da: 'Kryptografisk forseglet rapport',
    sv: 'Kryptografiskt förseglad rapport',
    nb: 'Kryptografisk forseglet rapport',
    ru: 'Криптографически защищённый отчёт',
  },
  geo_timestamped_photos: {
    it: 'Foto di prova con posizione e ora',
    en: 'Proof photos with location and time',
    de: 'Nachweisfotos mit Standort und Uhrzeit',
    fr: 'Photos de preuve avec position et heure',
    es: 'Fotos con GPS y marca de tiempo',
    nl: 'Bewijsfoto\'s met locatie en tijd',
    pt: 'Fotos com GPS e marca temporal',
    da: 'Billeder med GPS og tidsstempel',
    sv: 'Foton med GPS och tidsstämpel',
    nb: 'Bilder med GPS og tidsstempel',
    ru: 'Фото с GPS и меткой времени',
  },
  client_verification: {
    it: 'Verifica indipendente del cliente',
    en: 'Independent client verification',
    de: 'Unabhängige Kundenverifikation',
    fr: 'Vérification indépendante par le client',
    es: 'Verificación independiente del cliente',
    nl: 'Onafhankelijke controle door de klant',
    pt: 'Verificação independente do cliente',
    da: 'Uafhængig kundeverifikation',
    sv: 'Oberoende kundverifiering',
    nb: 'Uavhengig kundeverifisering',
    ru: 'Независимая проверка клиентом',
  },
  time_tracking: {
    it: 'Registrazione delle ore',
    en: 'Hours recording',
    de: 'Erfassung der Arbeitszeit',
    fr: 'Enregistrement des heures',
    es: 'Seguimiento del tiempo',
    nl: 'Registratie van de uren',
    pt: 'Controlo de horas',
    da: 'Tidsregistrering',
    sv: 'Tidsregistrering',
    nb: 'Tidsregistrering',
    ru: 'Учёт рабочего времени',
  },
  mobile_app: {
    it: 'App mobile Android/iOS',
    en: 'Mobile app Android/iOS',
    de: 'Mobile App Android/iOS',
    fr: 'Application mobile Android/iOS',
    es: 'App móvil Android/iOS',
    nl: 'Mobiele app voor Android/iOS',
    pt: 'App móvel Android/iOS',
    da: 'Mobilapp Android/iOS',
    sv: 'Mobilapp Android/iOS',
    nb: 'Mobilapp Android/iOS',
    ru: 'Мобильное приложение Android/iOS',
  },
  builtin_messaging: {
    it: 'Messaggistica interna',
    en: 'Built-in messaging',
    de: 'Integriertes Messaging',
    fr: 'Messagerie interne',
    es: 'Mensajería integrada',
    nl: 'Interne berichten',
    pt: 'Mensagens integradas',
    da: 'Indbygget meddelelser',
    sv: 'Inbyggd meddelandetjänst',
    nb: 'Innebygd meldingstjeneste',
    ru: 'Встроенный чат',
  },
  payroll_export: {
    it: 'Export presenze/paghe',
    en: 'Payroll/attendance export',
    de: 'Lohn-/Anwesenheits-Export',
    fr: 'Export présences/paie',
    es: 'Exportación de asistencia/nómina',
    nl: 'Export van aanwezigheid/salarissen',
    pt: 'Exportação de presenças/folha',
    da: 'Eksport af tilstedeværelse/løn',
    sv: 'Export av närvaro/lön',
    nb: 'Eksport av oppmøte/lønn',
    ru: 'Экспорт посещаемости/зарплат',
  },
  free_plan: {
    it: 'Piano gratuito',
    en: 'Free plan',
    de: 'Kostenloser Plan',
    fr: 'Formule gratuite',
    es: 'Plan gratuito',
    nl: 'Gratis abonnement',
    pt: 'Plano gratuito',
    da: 'Gratis plan',
    sv: 'Gratis plan',
    nb: 'Gratis plan',
    ru: 'Бесплатный тариф',
  },
  multi_site_jobs: {
    it: 'Gestione commesse multi-sito',
    en: 'Multi-site job management',
    de: 'Multi-Standort-Auftragsverwaltung',
    fr: 'Gestion de chantiers multi-sites',
    es: 'Gestión de obras multi-sitio',
    nl: 'Opdrachtenbeheer voor meerdere locaties',
    pt: 'Gestão de obras multi-local',
    da: 'Multi-site jobstyring',
    sv: 'Multi-site jobbhantering',
    nb: 'Multi-site jobbstyring',
    ru: 'Управление мультисайтовыми работами',
  },
  gdpr_geo_compliance: {
    it: 'Posizione solo alla timbratura, mai in continuo',
    en: 'Location only at clock-in, never continuous',
    de: 'Standort nur beim Stempeln, nie durchgehend',
    fr: 'Position uniquement au pointage, jamais en continu',
    es: 'Geolocalización conforme al RGPD',
    nl: 'Locatie alleen bij de registratie, nooit doorlopend',
    pt: 'Geolocalização em conformidade com RGPD',
    da: 'GDPR-kompatibel geolokation',
    sv: 'GDPR-kompatibel geolokalisering',
    nb: 'GDPR-kompatibel geolokasjon',
    ru: 'GDPR-совместимая геолокация',
  },
  auto_gps_notice_signed: {
    it: 'Informativa GPS firmata nell\'app prima di timbrare',
    en: 'GPS notice signed in the app before clocking in',
    de: 'GPS-Datenschutzinformation vor dem Stempeln in der App unterschrieben',
    fr: 'Information GPS signée dans l’application avant de pointer',
    es: 'Aviso GPS automático firmado',
    nl: 'GPS-verklaring ondertekend in de app vóór het registreren',
    pt: 'Aviso GPS automático assinado',
    da: 'Automatisk GPS-meddelelse med signatur',
    sv: 'Auto GPS-information med signatur',
    nb: 'Automatisk GPS-melding med signatur',
    ru: 'Авто GPS-уведомление с подписью',
  },
};

/** GeoTapp's feature vector, fixed across all competitor comparisons. */
export const GEOTAPP_FEATURES: Record<FeatureKey, boolean> = {
  gps_verified_at_site: true,
  sealed_report: true,
  geo_timestamped_photos: true,
  client_verification: true,
  time_tracking: true,
  mobile_app: true,
  builtin_messaging: true,
  payroll_export: true,
  free_plan: false, // GeoTapp ha trial 14gg, non free plan permanente
  multi_site_jobs: true,
  gdpr_geo_compliance: true,
  auto_gps_notice_signed: true,
};

export interface Competitor {
  id: string;
  name: string;
  homepage: string;
  /** Entry-plan pricing in EUR per seat per month (rough, for orientation). */
  pricingFromEur: number | null;
  /** Tagline cosa-è-questo-tool per locale. */
  tagline: LocalizedString;
  /** Feature vector aligned to FEATURE_KEYS. */
  features: Record<FeatureKey, boolean>;
}

/**
 * 11 competitor profiles. Data derived from public pricing pages + the existing
 * static /confronto/geotapp-vs-{competitor}/ pages.
 */
export const COMPETITORS: Competitor[] = [
  {
    id: 'connecteam',
    name: 'Connecteam',
    homepage: 'https://connecteam.com/',
    pricingFromEur: 29,
    tagline: {
      it: 'Comunicazione, gestione del personale e timbrature in un\'unica app per chi lavora fuori ufficio. Molto diffusa negli Stati Uniti.',
      en: 'Communication, HR and time tracking in one app for people who work away from a desk. Widely used in the United States.',
      de: 'Kommunikation, Personalverwaltung und Zeiterfassung in einer App für alle, die nicht am Schreibtisch arbeiten. In den USA weit verbreitet.',
      nl: 'Communicatie, personeelsbeheer en registraties in één app voor wie buiten kantoor werkt. Veel gebruikt in de Verenigde Staten.',
      fr: 'Communication, gestion du personnel et pointage dans une seule application pour celles et ceux qui travaillent hors du bureau. Très répandue aux États-Unis.',
    },
    features: {
      gps_verified_at_site: false,
      sealed_report: false,
      geo_timestamped_photos: false,
      client_verification: false,
      time_tracking: true,
      mobile_app: true,
      builtin_messaging: true,
      payroll_export: true,
      free_plan: true,
      multi_site_jobs: false,
      gdpr_geo_compliance: false,
      auto_gps_notice_signed: false,
    },
  },
  {
    id: 'hubstaff',
    name: 'Hubstaff',
    homepage: 'https://hubstaff.com/',
    pricingFromEur: 7,
    tagline: {
      it: 'Registrazione del tempo con screenshot e monitoraggio dell\'attività. Pensato per team remoti al computer, non per chi lavora sul campo.',
      en: 'Time tracking with screenshots and activity monitoring. Built for remote teams at a computer, not for field work.',
      de: 'Zeiterfassung mit Screenshots und Aktivitätsüberwachung. Gedacht für Remote-Teams am Computer, nicht für die Arbeit vor Ort.',
      nl: 'Tijdregistratie met schermafbeeldingen en monitoring van de activiteit. Bedoeld voor teams op afstand achter de computer, niet voor wie in het veld werkt.',
      fr: 'Suivi du temps avec captures d’écran et surveillance de l’activité. Conçu pour des équipes à distance devant un ordinateur, pas pour le travail sur le terrain.',
    },
    features: {
      gps_verified_at_site: false,
      sealed_report: false,
      geo_timestamped_photos: false,
      client_verification: false,
      time_tracking: true,
      mobile_app: true,
      builtin_messaging: false,
      payroll_export: true,
      free_plan: true,
      multi_site_jobs: false,
      gdpr_geo_compliance: false,
      auto_gps_notice_signed: false,
    },
  },
  {
    id: 'clockify',
    name: 'Clockify',
    homepage: 'https://clockify.me/',
    pricingFromEur: 4,
    tagline: {
      it: 'Registrazione del tempo gratuita e senza limiti. Ottimo per freelance e uffici, poco adatto al lavoro sul campo.',
      en: 'Free, unlimited time tracking. Great for freelancers and offices, a poor fit for field work.',
      de: 'Kostenlose Zeiterfassung ohne Begrenzung. Sehr gut für Freelancer und Büros, wenig geeignet für die Arbeit vor Ort.',
      nl: 'Gratis tijdregistratie zonder beperkingen. Uitstekend voor zelfstandigen en kantoren, weinig geschikt voor werk in het veld.',
      fr: 'Suivi du temps gratuit et sans limite. Très bien pour les indépendants et les bureaux, peu adapté au travail sur le terrain.',
    },
    features: {
      gps_verified_at_site: false,
      sealed_report: false,
      geo_timestamped_photos: false,
      client_verification: false,
      time_tracking: true,
      mobile_app: true,
      builtin_messaging: false,
      payroll_export: true,
      free_plan: true,
      multi_site_jobs: false,
      gdpr_geo_compliance: false,
      auto_gps_notice_signed: false,
    },
  },
  {
    id: 'jibble',
    name: 'Jibble',
    homepage: 'https://www.jibble.io/',
    pricingFromEur: 3,
    tagline: {
      it: 'Presenze con riconoscimento facciale e GPS di base. Piano gratuito generoso, ma niente prova del lavoro svolto.',
      en: 'Attendance with face recognition and basic GPS. Generous free plan, but no proof of the work done.',
      de: 'Anwesenheitserfassung mit Gesichtserkennung und einfachem GPS. Großzügiger Gratistarif, aber kein Nachweis der geleisteten Arbeit.',
      nl: 'Aanwezigheid met gezichtsherkenning en eenvoudige gps. Ruim gratis abonnement, maar geen bewijs van het uitgevoerde werk.',
      fr: 'Présences avec reconnaissance faciale et GPS basique. Formule gratuite généreuse, mais pas de preuve du travail effectué.',
    },
    features: {
      gps_verified_at_site: false,
      sealed_report: false,
      geo_timestamped_photos: false,
      client_verification: false,
      time_tracking: true,
      mobile_app: true,
      builtin_messaging: false,
      payroll_export: true,
      free_plan: true,
      multi_site_jobs: false,
      gdpr_geo_compliance: false,
      auto_gps_notice_signed: false,
    },
  },
  {
    id: 'personio',
    name: 'Personio',
    homepage: 'https://www.personio.com/',
    pricingFromEur: null,
    tagline: {
      it: 'Suite HR completa: anagrafica, assenze, onboarding e paghe. Non pensata per la prova del lavoro sul campo.',
      en: 'Full HR suite: records, absences, onboarding and payroll. Not built for field proof of work.',
      de: 'Vollständige HR-Suite: Stammdaten, Abwesenheiten, Onboarding und Lohn. Nicht für Außendienst-Nachweise gemacht.',
      nl: 'Complete HR-suite: personeelsdossiers, afwezigheid, onboarding en salaris. Niet bedoeld voor bewijs van werk in het veld.',
      fr: 'Suite RH complète : dossiers du personnel, absences, intégration et paie. Non conçue pour la preuve du travail sur le terrain.',
    },
    features: {
      gps_verified_at_site: false,
      sealed_report: false,
      geo_timestamped_photos: false,
      client_verification: false,
      time_tracking: true,
      mobile_app: true,
      builtin_messaging: false,
      payroll_export: true,
      free_plan: false,
      multi_site_jobs: false,
      gdpr_geo_compliance: false,
      auto_gps_notice_signed: false,
    },
  },
  {
    id: 'sage',
    name: 'Sage',
    homepage: 'https://www.sage.com/',
    pricingFromEur: null,
    tagline: {
      it: 'Gestionale: contabilità, fatturazione, paghe e HR (Sage HR). Non pensato per la prova del lavoro sul campo.',
      en: 'Business suite: accounting, invoicing, payroll and HR (Sage HR). Not built for field proof of work.',
      de: 'Business-Suite: Buchhaltung, Rechnungen, Lohn und HR (Sage HR). Nicht für Außendienst-Nachweise gemacht.',
      nl: 'Bedrijfssoftware: boekhouding, facturering, salaris en HR (Sage HR). Niet bedoeld voor bewijs van werk in het veld.',
      fr: 'Logiciel de gestion : comptabilité, facturation, paie et RH (Sage HR). Non conçu pour la preuve du travail sur le terrain.',
    },
    features: {
      gps_verified_at_site: false,
      sealed_report: false,
      geo_timestamped_photos: false,
      client_verification: false,
      time_tracking: true,
      mobile_app: true,
      builtin_messaging: false,
      payroll_export: true,
      free_plan: false,
      multi_site_jobs: false,
      gdpr_geo_compliance: false,
      auto_gps_notice_signed: false,
    },
  },
  {
    id: 'libemax',
    name: 'Libemax',
    homepage: 'https://www.libemax.com/',
    pricingFromEur: 12,
    tagline: {
      it: 'App italiana di rilevazione presenze molto diffusa: GPS, QR, NFC e geofence. Niente report sigillato per il committente.',
      en: 'Widely used Italian attendance app: GPS, QR, NFC and geofence. No sealed report for the client.',
      de: 'In Italien weit verbreitete App zur Anwesenheitserfassung: GPS, QR, NFC und Geofence. Kein versiegelter Bericht für den Auftraggeber.',
      nl: 'In Italië veel gebruikte app voor aanwezigheidsregistratie: gps, QR, NFC en geofence. Geen verzegeld rapport voor de opdrachtgever.',
      fr: 'Application italienne de suivi des présences très répandue : GPS, QR, NFC et geofence. Pas de rapport scellé pour le donneur d’ordre.',
    },
    features: {
      gps_verified_at_site: true, // ha GPS ma non sealed/timestamped come GeoTapp
      sealed_report: false,
      geo_timestamped_photos: false,
      client_verification: false,
      time_tracking: true,
      mobile_app: true,
      builtin_messaging: false,
      payroll_export: true,
      free_plan: false,
      multi_site_jobs: true,
      gdpr_geo_compliance: false,
      auto_gps_notice_signed: false,
    },
  },
  {
    id: 'blink',
    name: 'Blink',
    homepage: 'https://www.blink.de/',
    pricingFromEur: null,
    tagline: {
      it: 'Software tedesco per le imprese di pulizia: timbratura, attività e comunicazione del team. Niente report sigillato per il committente.',
      en: 'German software for cleaning companies: clock-in, tasks and team communication. No sealed report for the client.',
      de: 'Deutsche Software für Reinigungsbetriebe: Stempeln, Aufgaben und Teamkommunikation. Kein versiegelter Bericht für den Auftraggeber.',
      nl: 'Duitse software voor schoonmaakbedrijven: registratie, taken en teamcommunicatie. Geen verzegeld rapport voor de opdrachtgever.',
      fr: 'Logiciel allemand pour les entreprises de nettoyage : pointage, tâches et communication d’équipe. Pas de rapport scellé pour le donneur d’ordre.',
    },
    features: {
      gps_verified_at_site: false,
      sealed_report: false,
      geo_timestamped_photos: false,
      client_verification: false,
      time_tracking: true,
      mobile_app: true,
      builtin_messaging: true,
      payroll_export: false,
      free_plan: false,
      multi_site_jobs: true,
      gdpr_geo_compliance: false,
      auto_gps_notice_signed: false,
    },
  },
  {
    id: 'nobadge',
    name: 'NoBadge',
    homepage: 'https://nobadge.com/',
    pricingFromEur: 5,
    tagline: {
      it: 'Timbrature digitali italiane con GPS e QR code. Semplice e leggero, ma niente foto di prova né sigillo.',
      en: 'Italian digital clock-in with GPS and QR code. Simple and lightweight, but no proof photos or seal.',
      de: 'Italienische digitale Stempelung mit GPS und QR-Code. Einfach und schlank, aber keine Nachweisfotos und kein Siegel.',
      nl: 'Italiaanse digitale registratie met gps en QR-code. Eenvoudig en licht, maar geen bewijsfoto\'s en geen verzegeling.',
      fr: 'Pointage numérique italien avec GPS et QR code. Simple et léger, mais sans photos de preuve ni scellé.',
    },
    features: {
      gps_verified_at_site: true,
      sealed_report: false,
      geo_timestamped_photos: false,
      client_verification: false,
      time_tracking: true,
      mobile_app: true,
      builtin_messaging: false,
      payroll_export: true,
      free_plan: false,
      multi_site_jobs: false,
      gdpr_geo_compliance: false,
      auto_gps_notice_signed: false,
    },
  },
  {
    id: 'zucchetti',
    name: 'Zucchetti',
    homepage: 'https://www.zucchetti.it/',
    pricingFromEur: null,
    tagline: {
      it: 'La suite HR italiana per eccellenza, dalle presenze al cedolino. Timbratura con geofence e badge NFC, niente prova per il committente.',
      en: 'A widely used Italian HR suite, from attendance to payslip. Geofenced clock-in and NFC badges, no proof for the client.',
      de: 'Eine in Italien weit verbreitete HR-Suite, von der Zeiterfassung bis zur Lohnabrechnung. Stempeln mit Geofence und NFC-Badges, kein Nachweis für den Auftraggeber.',
      nl: 'De Italiaanse HR-suite bij uitstek, van aanwezigheid tot loonstrook. Registratie met geofence en NFC-badges, geen bewijs voor de opdrachtgever.',
      fr: 'La suite RH italienne par excellence, des présences au bulletin de paie. Pointage avec geofence et badges NFC, pas de preuve pour le donneur d’ordre.',
    },
    features: {
      gps_verified_at_site: true,
      sealed_report: false,
      geo_timestamped_photos: false,
      client_verification: false,
      time_tracking: true,
      mobile_app: true,
      builtin_messaging: true,
      payroll_export: true,
      free_plan: false,
      multi_site_jobs: true,
      gdpr_geo_compliance: false,
      auto_gps_notice_signed: false,
    },
  },
  {
    id: 'factorial',
    name: 'Factorial',
    homepage: 'https://factorialhr.com/',
    pricingFromEur: 6,
    tagline: {
      it: 'Piattaforma HR spagnola per le PMI, con ferie e assenze in ordine. Geolocalizzazione facoltativa sulla timbratura, senza controllo delle posizioni simulate.',
      en: 'Spanish HR platform for SMEs, keeping leave and absences in order. Optional geolocation on clock-in, with no check for spoofed locations.',
      de: 'Spanische HR-Plattform für KMU, mit geordneten Urlaubs- und Abwesenheitsdaten. Ortung beim Stempeln optional, ohne Prüfung auf gefälschte Standorte.',
      nl: 'Spaans HR-platform voor het MKB, met verlof en afwezigheid op orde. Geolocatie bij de registratie is optioneel, zonder controle op gesimuleerde locaties.',
      fr: 'Plateforme RH espagnole pour les PME, avec congés et absences bien tenus. Géolocalisation facultative au pointage, sans contrôle des positions simulées.',
    },
    features: {
      gps_verified_at_site: true,
      sealed_report: false,
      geo_timestamped_photos: false,
      client_verification: false,
      time_tracking: true,
      mobile_app: true,
      builtin_messaging: true,
      payroll_export: true,
      free_plan: false,
      multi_site_jobs: true,
      gdpr_geo_compliance: false,
      auto_gps_notice_signed: false,
    },
  },
];

/** Helper: prendi il label feature nella locale richiesta con fallback EN/IT. */
export function getFeatureLabel(key: FeatureKey, locale: string): string {
  const lo = locale as keyof LocalizedString;
  const labels = FEATURE_LABELS[key];
  return labels[lo] ?? labels.en ?? labels.it ?? key;
}

/** Helper: tagline competitor in locale con fallback EN/IT. */
export function getCompetitorTagline(c: Competitor, locale: string): string {
  const lo = locale as keyof LocalizedString;
  return c.tagline[lo] ?? c.tagline.en ?? c.tagline.it ?? '';
}
