/**
 * Le parole della schermata di conversione, in tutte le lingue del prodotto.
 *
 * Stanno in un file loro perche' la pagina e' gia' densa di logica e perche'
 * questa e' la schermata dove si incassa: chi corregge una frase non deve
 * passare in mezzo ai conti. Fino all'08/09/2026 esistevano solo it/en/de e
 * un cliente olandese o danese pagava leggendo l'inglese.
 *
 * La clausola di durata minima NON e' qui: resta in italiano nel componente,
 * testo approvato dal legale.
 */

export type UiLocale = 'it' | 'en' | 'de' | 'fr' | 'es' | 'nl' | 'pt' | 'da' | 'nb' | 'sv' | 'ru';

export const UI_LOCALES: UiLocale[] = ['it', 'en', 'de', 'fr', 'es', 'nl', 'pt', 'da', 'nb', 'sv', 'ru'];

export const BCP47: Record<UiLocale, string> = {
  it: 'it-IT', en: 'en-GB', de: 'de-DE', fr: 'fr-FR', es: 'es-ES', nl: 'nl-NL',
  pt: 'pt-PT', da: 'da-DK', nb: 'nb-NO', sv: 'sv-SE', ru: 'ru-RU',
};

export type Strings = {
  title: string;
  subtitle: string;
  recommendedFor: string;
  recTitle: (plan: string) => string;
  recIntro: string;
  reasonTt: (n: number) => string;
  reasonOffice: (n: number) => string;
  reasonFlow: (n: number) => string;
  reasonNone: string;
  recChange: string;
  billingMonthly: string;
  billingAnnual: string;
  billingSave: (amount: string) => string;
  planCeiling: (n: number) => string;
  planCeilingUnlimited: string;
  seatsTitle: string;
  seatsHelp: string;
  seatsUnit: (price: string) => string;
  seatsDecrease: string;
  seatsIncrease: string;
  bumpUp: (plan: string, n: number) => string;
  bumpDownHint: (plan: string) => string;
  bumpDownAction: (plan: string) => string;
  seatsTrimmed: (plan: string, n: number) => string;
  officeTitle: string;
  officeHelp: string;
  officeAnnualOnly: string;
  lineFlow: (plan: string) => string;
  lineTt: (n: number) => string;
  lineOffice: (n: number) => string;
  totalLabel: string;
  perYear: string;
  perMonth: string;
  vatExcluded: string;
  laterNote: string;
  vatLabel: string;
  vatPlaceholder: string;
  termsPrefix: string;
  termsLink: string;
  privacyPrefix: string;
  privacyLink: string;
  submit: string;
  loading: string;
  missingTenant: string;
  vatRequired: string;
  minTermRequired: string;
  generic: string;
  alreadySubscribed: string;
};

export const UI: Record<UiLocale, Strings> = {
  it: {
    title: 'Attiva il tuo abbonamento',
    subtitle: 'Un ultimo passaggio e GeoTapp resta acceso.',
    recommendedFor: 'Consigliato per te',
    recTitle: (plan) => `Ti consigliamo Flow ${plan}`,
    recIntro: 'In base a come hai usato la prova:',
    reasonTt: (n) => `hai tenuto attive ${n} postazioni TimeTracker`,
    reasonOffice: (n) => `${n} persone timbrano dall'ufficio`,
    reasonFlow: (n) => `${n} persone hanno usato il pannello Flow`,
    reasonNone: 'durante la prova non hai attivato postazioni: ti proponiamo il piano con cui l\'hai aperta',
    recChange: 'Puoi cambiare piano, aggiungere o togliere postazioni: il totale qui sotto si aggiorna subito.',
    billingMonthly: 'Mensile',
    billingAnnual: 'Annuale',
    billingSave: (amount) => `risparmi ${amount}`,
    planCeiling: (n) => `fino a ${n} postazioni TimeTracker`,
    planCeilingUnlimited: 'postazioni TimeTracker senza limite',
    seatsTitle: 'Postazioni TimeTracker',
    seatsHelp: 'Una per ogni operatore che timbra dal telefono. Si pagano a parte, nessun piano le include.',
    seatsUnit: (price) => `${price} a operatore`,
    seatsDecrease: 'Una postazione in meno',
    seatsIncrease: 'Una postazione in piu\'',
    bumpUp: (plan, n) => `Per ${n} postazioni serve Flow ${plan}: l'abbiamo selezionato per te.`,
    bumpDownHint: (plan) => `Con queste postazioni ti basterebbe Flow ${plan}.`,
    bumpDownAction: (plan) => `Passa a ${plan}`,
    seatsTrimmed: (plan, n) => `Flow ${plan} regge ${n} postazioni: abbiamo portato la quantita' a ${n}.`,
    officeTitle: 'Posti Timbratura da ufficio',
    officeHelp: 'Per chi timbra dal computer, senza telefono aziendale.',
    officeAnnualOnly: 'Disponibili solo con pagamento annuale.',
    lineFlow: (plan) => `Flow ${plan}`,
    lineTt: (n) => `${n} postazioni TimeTracker`,
    lineOffice: (n) => `${n} posti Timbratura`,
    totalLabel: 'Totale',
    perYear: 'all\'anno',
    perMonth: 'al mese',
    vatExcluded: 'IVA esclusa',
    laterNote: 'Potrai aggiungere postazioni quando vuoi: pagherai solo la differenza per i mesi che restano.',
    vatLabel: 'Partita IVA',
    vatPlaceholder: 'es. IT01234567890',
    termsPrefix: 'Ho letto e accetto le',
    termsLink: 'Condizioni di servizio',
    privacyPrefix: 'Ho letto la',
    privacyLink: 'Privacy Policy',
    submit: 'Vai al pagamento',
    loading: 'Un attimo...',
    missingTenant: 'Link non valido: manca il riferimento all\'account.',
    vatRequired: 'Inserisci la partita IVA.',
    minTermRequired: 'Devi approvare specificamente la clausola di durata minima.',
    generic: 'Qualcosa e\' andato storto. Riprova.',
    alreadySubscribed: 'Questo account ha gia\' un abbonamento attivo.',
  },
  en: {
    title: 'Activate your subscription',
    subtitle: 'One last step and GeoTapp stays on.',
    recommendedFor: 'Recommended for you',
    recTitle: (plan) => `We recommend Flow ${plan}`,
    recIntro: 'Based on how you used the trial:',
    reasonTt: (n) => `you kept ${n} TimeTracker seats active`,
    reasonOffice: (n) => `${n} people clock in from the office`,
    reasonFlow: (n) => `${n} people used the Flow panel`,
    reasonNone: 'you did not activate any seat during the trial, so we suggest the plan you started with',
    recChange: 'Change the plan, add or remove seats: the total below updates instantly.',
    billingMonthly: 'Monthly',
    billingAnnual: 'Yearly',
    billingSave: (amount) => `save ${amount}`,
    planCeiling: (n) => `up to ${n} TimeTracker seats`,
    planCeilingUnlimited: 'unlimited TimeTracker seats',
    seatsTitle: 'TimeTracker seats',
    seatsHelp: 'One per field operator clocking in from their phone. Billed separately: no plan includes them.',
    seatsUnit: (price) => `${price} per operator`,
    seatsDecrease: 'One seat fewer',
    seatsIncrease: 'One seat more',
    bumpUp: (plan, n) => `${n} seats require Flow ${plan}: we selected it for you.`,
    bumpDownHint: (plan) => `With these seats Flow ${plan} would be enough.`,
    bumpDownAction: (plan) => `Switch to ${plan}`,
    seatsTrimmed: (plan, n) => `Flow ${plan} holds ${n} seats: we set the quantity to ${n}.`,
    officeTitle: 'Office clock-in seats',
    officeHelp: 'For people clocking in from a computer, without a company phone.',
    officeAnnualOnly: 'Available with yearly billing only.',
    lineFlow: (plan) => `Flow ${plan}`,
    lineTt: (n) => `${n} TimeTracker seats`,
    lineOffice: (n) => `${n} office clock-in seats`,
    totalLabel: 'Total',
    perYear: 'per year',
    perMonth: 'per month',
    vatExcluded: 'VAT excluded',
    laterNote: 'You can add seats whenever you need: you will only pay the difference for the remaining months.',
    vatLabel: 'VAT number',
    vatPlaceholder: 'e.g. IT01234567890',
    termsPrefix: 'I have read and accept the',
    termsLink: 'Terms of Service',
    privacyPrefix: 'I have read the',
    privacyLink: 'Privacy Policy',
    submit: 'Go to payment',
    loading: 'One moment...',
    missingTenant: 'Invalid link: the account reference is missing.',
    vatRequired: 'Please enter your VAT number.',
    minTermRequired: 'You must specifically approve the minimum-term clause.',
    generic: 'Something went wrong. Please try again.',
    alreadySubscribed: 'This account already has an active subscription.',
  },
  de: {
    title: 'Abonnement aktivieren',
    subtitle: 'Ein letzter Schritt, und GeoTapp läuft weiter.',
    recommendedFor: 'Für Sie empfohlen',
    recTitle: (plan) => `Wir empfehlen Flow ${plan}`,
    recIntro: 'Auf Basis Ihrer Testphase:',
    reasonTt: (n) => `Sie hatten ${n} TimeTracker-Plätze aktiv`,
    reasonOffice: (n) => `${n} Personen stempeln vom Büro aus`,
    reasonFlow: (n) => `${n} Personen haben das Flow-Panel genutzt`,
    reasonNone: 'Sie haben in der Testphase keinen Platz aktiviert: Wir schlagen den Tarif vor, mit dem Sie gestartet sind',
    recChange: 'Tarif wechseln, Plätze hinzufügen oder entfernen: Die Summe unten aktualisiert sich sofort.',
    billingMonthly: 'Monatlich',
    billingAnnual: 'Jährlich',
    billingSave: (amount) => `${amount} sparen`,
    planCeiling: (n) => `bis zu ${n} TimeTracker-Plätze`,
    planCeilingUnlimited: 'unbegrenzte TimeTracker-Plätze',
    seatsTitle: 'TimeTracker-Plätze',
    seatsHelp: 'Einer pro Mitarbeiter, der per Handy stempelt. Sie werden separat berechnet, kein Tarif enthält sie.',
    seatsUnit: (price) => `${price} pro Mitarbeiter`,
    seatsDecrease: 'Ein Platz weniger',
    seatsIncrease: 'Ein Platz mehr',
    bumpUp: (plan, n) => `Für ${n} Plätze ist Flow ${plan} nötig: Wir haben ihn ausgewählt.`,
    bumpDownHint: (plan) => `Mit diesen Plätzen würde Flow ${plan} reichen.`,
    bumpDownAction: (plan) => `Zu ${plan} wechseln`,
    seatsTrimmed: (plan, n) => `Flow ${plan} trägt ${n} Plätze: Wir haben die Menge auf ${n} gesetzt.`,
    officeTitle: 'Büro-Stempelplätze',
    officeHelp: 'Für alle, die am Computer stempeln, ohne Firmenhandy.',
    officeAnnualOnly: 'Nur bei jährlicher Zahlung verfügbar.',
    lineFlow: (plan) => `Flow ${plan}`,
    lineTt: (n) => `${n} TimeTracker-Plätze`,
    lineOffice: (n) => `${n} Büro-Stempelplätze`,
    totalLabel: 'Gesamt',
    perYear: 'pro Jahr',
    perMonth: 'pro Monat',
    vatExcluded: 'zzgl. MwSt.',
    laterNote: 'Sie können jederzeit Plätze hinzufügen: Sie zahlen nur die Differenz für die verbleibenden Monate.',
    vatLabel: 'USt-IdNr.',
    vatPlaceholder: 'z. B. DE123456789',
    termsPrefix: 'Ich habe die',
    termsLink: 'Nutzungsbedingungen',
    privacyPrefix: 'Ich habe die',
    privacyLink: 'Datenschutzerklärung',
    submit: 'Zur Zahlung',
    loading: 'Einen Moment...',
    missingTenant: 'Ungültiger Link: Der Kontobezug fehlt.',
    vatRequired: 'Bitte geben Sie Ihre USt-IdNr. ein.',
    minTermRequired: 'Sie müssen die Mindestlaufzeit-Klausel ausdrücklich annehmen.',
    generic: 'Etwas ist schiefgelaufen. Bitte versuchen Sie es erneut.',
    alreadySubscribed: 'Für dieses Konto besteht bereits ein aktives Abonnement.',
  },
  fr: {
    title: 'Activez votre abonnement',
    subtitle: 'Une dernière étape et GeoTapp reste actif.',
    recommendedFor: 'Recommandé pour vous',
    recTitle: (plan) => `Nous vous conseillons Flow ${plan}`,
    recIntro: 'D\'après votre utilisation de l\'essai :',
    reasonTt: (n) => `vous avez gardé ${n} postes TimeTracker actifs`,
    reasonOffice: (n) => `${n} personnes pointent depuis le bureau`,
    reasonFlow: (n) => `${n} personnes ont utilisé le panneau Flow`,
    reasonNone: 'vous n\'avez activé aucun poste pendant l\'essai : nous proposons le plan avec lequel vous avez commencé',
    recChange: 'Changez de plan, ajoutez ou retirez des postes : le total ci-dessous se met à jour aussitôt.',
    billingMonthly: 'Mensuel',
    billingAnnual: 'Annuel',
    billingSave: (amount) => `économisez ${amount}`,
    planCeiling: (n) => `jusqu'à ${n} postes TimeTracker`,
    planCeilingUnlimited: 'postes TimeTracker illimités',
    seatsTitle: 'Postes TimeTracker',
    seatsHelp: 'Un par opérateur qui pointe depuis son téléphone. Facturés à part : aucun plan ne les inclut.',
    seatsUnit: (price) => `${price} par opérateur`,
    seatsDecrease: 'Un poste de moins',
    seatsIncrease: 'Un poste de plus',
    bumpUp: (plan, n) => `${n} postes exigent Flow ${plan} : nous l'avons sélectionné pour vous.`,
    bumpDownHint: (plan) => `Avec ces postes, Flow ${plan} suffirait.`,
    bumpDownAction: (plan) => `Passer à ${plan}`,
    seatsTrimmed: (plan, n) => `Flow ${plan} accepte ${n} postes : nous avons ramené la quantité à ${n}.`,
    officeTitle: 'Postes de pointage au bureau',
    officeHelp: 'Pour celles et ceux qui pointent depuis un ordinateur, sans téléphone professionnel.',
    officeAnnualOnly: 'Disponibles uniquement en paiement annuel.',
    lineFlow: (plan) => `Flow ${plan}`,
    lineTt: (n) => `${n} postes TimeTracker`,
    lineOffice: (n) => `${n} postes de pointage`,
    totalLabel: 'Total',
    perYear: 'par an',
    perMonth: 'par mois',
    vatExcluded: 'HT',
    laterNote: 'Vous pourrez ajouter des postes quand vous voulez : vous ne paierez que la différence pour les mois restants.',
    vatLabel: 'Numéro de TVA',
    vatPlaceholder: 'ex. FR12345678901',
    termsPrefix: 'J\'ai lu et j\'accepte les',
    termsLink: 'Conditions de service',
    privacyPrefix: 'J\'ai lu la',
    privacyLink: 'Politique de confidentialité',
    submit: 'Aller au paiement',
    loading: 'Un instant...',
    missingTenant: 'Lien non valide : la référence au compte est absente.',
    vatRequired: 'Veuillez saisir votre numéro de TVA.',
    minTermRequired: 'Vous devez approuver expressément la clause de durée minimale.',
    generic: 'Une erreur est survenue. Réessayez.',
    alreadySubscribed: 'Ce compte a déjà un abonnement actif.',
  },
  es: {
    title: 'Activa tu suscripción',
    subtitle: 'Un último paso y GeoTapp sigue funcionando.',
    recommendedFor: 'Recomendado para ti',
    recTitle: (plan) => `Te recomendamos Flow ${plan}`,
    recIntro: 'Según cómo has usado la prueba:',
    reasonTt: (n) => `has mantenido ${n} puestos TimeTracker activos`,
    reasonOffice: (n) => `${n} personas fichan desde la oficina`,
    reasonFlow: (n) => `${n} personas han usado el panel Flow`,
    reasonNone: 'durante la prueba no activaste ningún puesto: te proponemos el plan con el que empezaste',
    recChange: 'Cambia de plan, añade o quita puestos: el total de abajo se actualiza al instante.',
    billingMonthly: 'Mensual',
    billingAnnual: 'Anual',
    billingSave: (amount) => `ahorras ${amount}`,
    planCeiling: (n) => `hasta ${n} puestos TimeTracker`,
    planCeilingUnlimited: 'puestos TimeTracker sin límite',
    seatsTitle: 'Puestos TimeTracker',
    seatsHelp: 'Uno por cada operario que ficha desde el móvil. Se pagan aparte: ningún plan los incluye.',
    seatsUnit: (price) => `${price} por operario`,
    seatsDecrease: 'Un puesto menos',
    seatsIncrease: 'Un puesto más',
    bumpUp: (plan, n) => `Para ${n} puestos hace falta Flow ${plan}: lo hemos seleccionado por ti.`,
    bumpDownHint: (plan) => `Con estos puestos te bastaría Flow ${plan}.`,
    bumpDownAction: (plan) => `Cambiar a ${plan}`,
    seatsTrimmed: (plan, n) => `Flow ${plan} admite ${n} puestos: hemos ajustado la cantidad a ${n}.`,
    officeTitle: 'Puestos de fichaje de oficina',
    officeHelp: 'Para quien ficha desde el ordenador, sin móvil de empresa.',
    officeAnnualOnly: 'Disponibles solo con pago anual.',
    lineFlow: (plan) => `Flow ${plan}`,
    lineTt: (n) => `${n} puestos TimeTracker`,
    lineOffice: (n) => `${n} puestos de fichaje`,
    totalLabel: 'Total',
    perYear: 'al año',
    perMonth: 'al mes',
    vatExcluded: 'IVA no incluido',
    laterNote: 'Podrás añadir puestos cuando quieras: solo pagarás la diferencia por los meses que queden.',
    vatLabel: 'NIF / CIF',
    vatPlaceholder: 'ej. ESB12345678',
    termsPrefix: 'He leído y acepto las',
    termsLink: 'Condiciones del servicio',
    privacyPrefix: 'He leído la',
    privacyLink: 'Política de privacidad',
    submit: 'Ir al pago',
    loading: 'Un momento...',
    missingTenant: 'Enlace no válido: falta la referencia a la cuenta.',
    vatRequired: 'Introduce tu NIF/CIF.',
    minTermRequired: 'Debes aprobar expresamente la cláusula de duración mínima.',
    generic: 'Algo ha salido mal. Inténtalo de nuevo.',
    alreadySubscribed: 'Esta cuenta ya tiene una suscripción activa.',
  },
  nl: {
    title: 'Activeer je abonnement',
    subtitle: 'Nog één stap en GeoTapp blijft aan.',
    recommendedFor: 'Aanbevolen voor jou',
    recTitle: (plan) => `Wij raden Flow ${plan} aan`,
    recIntro: 'Op basis van je proefperiode:',
    reasonTt: (n) => `je hield ${n} TimeTracker-plaatsen actief`,
    reasonOffice: (n) => `${n} mensen klokken in vanaf kantoor`,
    reasonFlow: (n) => `${n} mensen gebruikten het Flow-paneel`,
    reasonNone: 'je hebt tijdens de proef geen plaats geactiveerd: we stellen het plan voor waarmee je begon',
    recChange: 'Wissel van plan, voeg plaatsen toe of haal ze weg: het totaal hieronder past zich direct aan.',
    billingMonthly: 'Maandelijks',
    billingAnnual: 'Jaarlijks',
    billingSave: (amount) => `bespaar ${amount}`,
    planCeiling: (n) => `tot ${n} TimeTracker-plaatsen`,
    planCeilingUnlimited: 'onbeperkt TimeTracker-plaatsen',
    seatsTitle: 'TimeTracker-plaatsen',
    seatsHelp: 'Eén per medewerker die met de telefoon inklokt. Apart gefactureerd: geen enkel plan bevat ze.',
    seatsUnit: (price) => `${price} per medewerker`,
    seatsDecrease: 'Eén plaats minder',
    seatsIncrease: 'Eén plaats meer',
    bumpUp: (plan, n) => `Voor ${n} plaatsen is Flow ${plan} nodig: we hebben het voor je gekozen.`,
    bumpDownHint: (plan) => `Met deze plaatsen zou Flow ${plan} genoeg zijn.`,
    bumpDownAction: (plan) => `Naar ${plan}`,
    seatsTrimmed: (plan, n) => `Flow ${plan} draagt ${n} plaatsen: we hebben het aantal op ${n} gezet.`,
    officeTitle: 'Kantoor-inklokplaatsen',
    officeHelp: 'Voor wie inklokt vanaf de computer, zonder zakelijke telefoon.',
    officeAnnualOnly: 'Alleen beschikbaar bij jaarlijkse betaling.',
    lineFlow: (plan) => `Flow ${plan}`,
    lineTt: (n) => `${n} TimeTracker-plaatsen`,
    lineOffice: (n) => `${n} kantoor-inklokplaatsen`,
    totalLabel: 'Totaal',
    perYear: 'per jaar',
    perMonth: 'per maand',
    vatExcluded: 'excl. btw',
    laterNote: 'Je kunt altijd plaatsen bijkopen: je betaalt alleen het verschil voor de resterende maanden.',
    vatLabel: 'Btw-nummer',
    vatPlaceholder: 'bijv. NL123456789B01',
    termsPrefix: 'Ik heb de',
    termsLink: 'Servicevoorwaarden',
    privacyPrefix: 'Ik heb het',
    privacyLink: 'Privacybeleid',
    submit: 'Naar de betaling',
    loading: 'Een moment...',
    missingTenant: 'Ongeldige link: de accountverwijzing ontbreekt.',
    vatRequired: 'Vul je btw-nummer in.',
    minTermRequired: 'Je moet de clausule over de minimumduur uitdrukkelijk goedkeuren.',
    generic: 'Er is iets misgegaan. Probeer het opnieuw.',
    alreadySubscribed: 'Dit account heeft al een actief abonnement.',
  },
  pt: {
    title: 'Ative a sua subscrição',
    subtitle: 'Falta um passo e o GeoTapp continua ligado.',
    recommendedFor: 'Recomendado para si',
    recTitle: (plan) => `Recomendamos o Flow ${plan}`,
    recIntro: 'Com base na forma como usou o período de teste:',
    reasonTt: (n) => `manteve ${n} postos TimeTracker ativos`,
    reasonOffice: (n) => `${n} pessoas picam o ponto no escritório`,
    reasonFlow: (n) => `${n} pessoas usaram o painel Flow`,
    reasonNone: 'não ativou nenhum posto durante o teste: propomos o plano com que começou',
    recChange: 'Mude de plano, acrescente ou retire postos: o total abaixo atualiza-se de imediato.',
    billingMonthly: 'Mensal',
    billingAnnual: 'Anual',
    billingSave: (amount) => `poupa ${amount}`,
    planCeiling: (n) => `até ${n} postos TimeTracker`,
    planCeilingUnlimited: 'postos TimeTracker sem limite',
    seatsTitle: 'Postos TimeTracker',
    seatsHelp: 'Um por cada operador que pica o ponto pelo telemóvel. Pagam-se à parte: nenhum plano os inclui.',
    seatsUnit: (price) => `${price} por operador`,
    seatsDecrease: 'Menos um posto',
    seatsIncrease: 'Mais um posto',
    bumpUp: (plan, n) => `${n} postos exigem o Flow ${plan}: selecionámo-lo por si.`,
    bumpDownHint: (plan) => `Com estes postos bastaria o Flow ${plan}.`,
    bumpDownAction: (plan) => `Mudar para ${plan}`,
    seatsTrimmed: (plan, n) => `O Flow ${plan} suporta ${n} postos: ajustámos a quantidade para ${n}.`,
    officeTitle: 'Postos de picagem no escritório',
    officeHelp: 'Para quem pica o ponto no computador, sem telemóvel da empresa.',
    officeAnnualOnly: 'Disponíveis apenas com pagamento anual.',
    lineFlow: (plan) => `Flow ${plan}`,
    lineTt: (n) => `${n} postos TimeTracker`,
    lineOffice: (n) => `${n} postos de picagem`,
    totalLabel: 'Total',
    perYear: 'por ano',
    perMonth: 'por mês',
    vatExcluded: 'IVA não incluído',
    laterNote: 'Poderá acrescentar postos quando quiser: paga apenas a diferença pelos meses que faltam.',
    vatLabel: 'NIF',
    vatPlaceholder: 'ex. PT123456789',
    termsPrefix: 'Li e aceito os',
    termsLink: 'Termos de Serviço',
    privacyPrefix: 'Li a',
    privacyLink: 'Política de Privacidade',
    submit: 'Ir para o pagamento',
    loading: 'Um momento...',
    missingTenant: 'Ligação inválida: falta a referência à conta.',
    vatRequired: 'Introduza o seu NIF.',
    minTermRequired: 'Tem de aprovar expressamente a cláusula de duração mínima.',
    generic: 'Algo correu mal. Tente novamente.',
    alreadySubscribed: 'Esta conta já tem uma subscrição ativa.',
  },
  da: {
    title: 'Aktivér dit abonnement',
    subtitle: 'Et sidste skridt, så kører GeoTapp videre.',
    recommendedFor: 'Anbefalet til dig',
    recTitle: (plan) => `Vi anbefaler Flow ${plan}`,
    recIntro: 'Ud fra din brug i prøveperioden:',
    reasonTt: (n) => `du har haft ${n} TimeTracker-pladser aktive`,
    reasonOffice: (n) => `${n} personer stempler ind fra kontoret`,
    reasonFlow: (n) => `${n} personer har brugt Flow-panelet`,
    reasonNone: 'du aktiverede ingen pladser i prøveperioden: vi foreslår den plan, du startede med',
    recChange: 'Skift plan, tilføj eller fjern pladser: totalen nedenfor opdateres med det samme.',
    billingMonthly: 'Månedligt',
    billingAnnual: 'Årligt',
    billingSave: (amount) => `spar ${amount}`,
    planCeiling: (n) => `op til ${n} TimeTracker-pladser`,
    planCeilingUnlimited: 'ubegrænsede TimeTracker-pladser',
    seatsTitle: 'TimeTracker-pladser',
    seatsHelp: 'Én pr. medarbejder, der stempler ind fra telefonen. Betales særskilt: ingen plan indeholder dem.',
    seatsUnit: (price) => `${price} pr. medarbejder`,
    seatsDecrease: 'Én plads færre',
    seatsIncrease: 'Én plads mere',
    bumpUp: (plan, n) => `${n} pladser kræver Flow ${plan}: vi har valgt den for dig.`,
    bumpDownHint: (plan) => `Med disse pladser ville Flow ${plan} være nok.`,
    bumpDownAction: (plan) => `Skift til ${plan}`,
    seatsTrimmed: (plan, n) => `Flow ${plan} rummer ${n} pladser: vi har sat antallet til ${n}.`,
    officeTitle: 'Kontor-stemplingspladser',
    officeHelp: 'Til dem, der stempler ind fra computeren uden firmatelefon.',
    officeAnnualOnly: 'Kun ved årlig betaling.',
    lineFlow: (plan) => `Flow ${plan}`,
    lineTt: (n) => `${n} TimeTracker-pladser`,
    lineOffice: (n) => `${n} kontor-stemplingspladser`,
    totalLabel: 'I alt',
    perYear: 'om året',
    perMonth: 'om måneden',
    vatExcluded: 'ekskl. moms',
    laterNote: 'Du kan tilføje pladser når som helst: du betaler kun forskellen for de resterende måneder.',
    vatLabel: 'CVR-nummer',
    vatPlaceholder: 'f.eks. DK12345678',
    termsPrefix: 'Jeg har læst og accepterer',
    termsLink: 'Servicevilkårene',
    privacyPrefix: 'Jeg har læst',
    privacyLink: 'Privatlivspolitikken',
    submit: 'Gå til betaling',
    loading: 'Et øjeblik...',
    missingTenant: 'Ugyldigt link: kontoreferencen mangler.',
    vatRequired: 'Indtast dit CVR-nummer.',
    minTermRequired: 'Du skal udtrykkeligt godkende klausulen om minimumsperiode.',
    generic: 'Noget gik galt. Prøv igen.',
    alreadySubscribed: 'Denne konto har allerede et aktivt abonnement.',
  },
  nb: {
    title: 'Aktiver abonnementet ditt',
    subtitle: 'Ett siste steg, så fortsetter GeoTapp.',
    recommendedFor: 'Anbefalt for deg',
    recTitle: (plan) => `Vi anbefaler Flow ${plan}`,
    recIntro: 'Basert på hvordan du brukte prøveperioden:',
    reasonTt: (n) => `du hadde ${n} TimeTracker-plasser aktive`,
    reasonOffice: (n) => `${n} personer stempler inn fra kontoret`,
    reasonFlow: (n) => `${n} personer brukte Flow-panelet`,
    reasonNone: 'du aktiverte ingen plasser i prøveperioden: vi foreslår planen du startet med',
    recChange: 'Bytt plan, legg til eller fjern plasser: totalen nedenfor oppdateres med en gang.',
    billingMonthly: 'Månedlig',
    billingAnnual: 'Årlig',
    billingSave: (amount) => `spar ${amount}`,
    planCeiling: (n) => `opptil ${n} TimeTracker-plasser`,
    planCeilingUnlimited: 'ubegrensede TimeTracker-plasser',
    seatsTitle: 'TimeTracker-plasser',
    seatsHelp: 'Én per ansatt som stempler inn fra telefonen. Faktureres separat: ingen plan inkluderer dem.',
    seatsUnit: (price) => `${price} per ansatt`,
    seatsDecrease: 'Én plass mindre',
    seatsIncrease: 'Én plass mer',
    bumpUp: (plan, n) => `${n} plasser krever Flow ${plan}: vi har valgt den for deg.`,
    bumpDownHint: (plan) => `Med disse plassene ville Flow ${plan} holde.`,
    bumpDownAction: (plan) => `Bytt til ${plan}`,
    seatsTrimmed: (plan, n) => `Flow ${plan} rommer ${n} plasser: vi satte antallet til ${n}.`,
    officeTitle: 'Kontor-stemplingsplasser',
    officeHelp: 'For dem som stempler inn fra datamaskinen, uten firmatelefon.',
    officeAnnualOnly: 'Kun ved årlig betaling.',
    lineFlow: (plan) => `Flow ${plan}`,
    lineTt: (n) => `${n} TimeTracker-plasser`,
    lineOffice: (n) => `${n} kontor-stemplingsplasser`,
    totalLabel: 'Totalt',
    perYear: 'per år',
    perMonth: 'per måned',
    vatExcluded: 'eks. mva.',
    laterNote: 'Du kan legge til plasser når du vil: du betaler bare differansen for månedene som gjenstår.',
    vatLabel: 'Organisasjonsnummer',
    vatPlaceholder: 'f.eks. NO123456789MVA',
    termsPrefix: 'Jeg har lest og godtar',
    termsLink: 'Vilkårene for tjenesten',
    privacyPrefix: 'Jeg har lest',
    privacyLink: 'Personvernerklæringen',
    submit: 'Gå til betaling',
    loading: 'Et øyeblikk...',
    missingTenant: 'Ugyldig lenke: kontoreferansen mangler.',
    vatRequired: 'Skriv inn organisasjonsnummeret.',
    minTermRequired: 'Du må uttrykkelig godkjenne klausulen om minstetid.',
    generic: 'Noe gikk galt. Prøv igjen.',
    alreadySubscribed: 'Denne kontoen har allerede et aktivt abonnement.',
  },
  sv: {
    title: 'Aktivera din prenumeration',
    subtitle: 'Ett sista steg, sedan fortsätter GeoTapp.',
    recommendedFor: 'Rekommenderas för dig',
    recTitle: (plan) => `Vi rekommenderar Flow ${plan}`,
    recIntro: 'Utifrån hur du använde provperioden:',
    reasonTt: (n) => `du hade ${n} TimeTracker-platser aktiva`,
    reasonOffice: (n) => `${n} personer stämplar in från kontoret`,
    reasonFlow: (n) => `${n} personer använde Flow-panelen`,
    reasonNone: 'du aktiverade inga platser under provperioden: vi föreslår planen du började med',
    recChange: 'Byt plan, lägg till eller ta bort platser: summan nedan uppdateras direkt.',
    billingMonthly: 'Månadsvis',
    billingAnnual: 'Årsvis',
    billingSave: (amount) => `spara ${amount}`,
    planCeiling: (n) => `upp till ${n} TimeTracker-platser`,
    planCeilingUnlimited: 'obegränsat med TimeTracker-platser',
    seatsTitle: 'TimeTracker-platser',
    seatsHelp: 'En per medarbetare som stämplar in med telefonen. Faktureras separat: ingen plan innehåller dem.',
    seatsUnit: (price) => `${price} per medarbetare`,
    seatsDecrease: 'En plats färre',
    seatsIncrease: 'En plats till',
    bumpUp: (plan, n) => `${n} platser kräver Flow ${plan}: vi har valt den åt dig.`,
    bumpDownHint: (plan) => `Med de här platserna skulle Flow ${plan} räcka.`,
    bumpDownAction: (plan) => `Byt till ${plan}`,
    seatsTrimmed: (plan, n) => `Flow ${plan} rymmer ${n} platser: vi satte antalet till ${n}.`,
    officeTitle: 'Kontorsstämplingsplatser',
    officeHelp: 'För den som stämplar in från datorn, utan företagstelefon.',
    officeAnnualOnly: 'Endast vid årsbetalning.',
    lineFlow: (plan) => `Flow ${plan}`,
    lineTt: (n) => `${n} TimeTracker-platser`,
    lineOffice: (n) => `${n} kontorsstämplingsplatser`,
    totalLabel: 'Totalt',
    perYear: 'per år',
    perMonth: 'per månad',
    vatExcluded: 'exkl. moms',
    laterNote: 'Du kan lägga till platser när du vill: du betalar bara mellanskillnaden för månaderna som återstår.',
    vatLabel: 'Momsregistreringsnummer',
    vatPlaceholder: 't.ex. SE123456789701',
    termsPrefix: 'Jag har läst och godkänner',
    termsLink: 'Användarvillkoren',
    privacyPrefix: 'Jag har läst',
    privacyLink: 'Integritetspolicyn',
    submit: 'Gå till betalning',
    loading: 'Ett ögonblick...',
    missingTenant: 'Ogiltig länk: kontoreferensen saknas.',
    vatRequired: 'Ange ditt momsregistreringsnummer.',
    minTermRequired: 'Du måste uttryckligen godkänna klausulen om minsta bindningstid.',
    generic: 'Något gick fel. Försök igen.',
    alreadySubscribed: 'Det här kontot har redan en aktiv prenumeration.',
  },
  ru: {
    title: 'Активируйте подписку',
    subtitle: 'Последний шаг — и GeoTapp продолжит работать.',
    recommendedFor: 'Рекомендуем вам',
    recTitle: (plan) => `Рекомендуем Flow ${plan}`,
    recIntro: 'Исходя из того, как вы использовали пробный период:',
    reasonTt: (n) => `у вас было активно мест TimeTracker: ${n}`,
    reasonOffice: (n) => `отмечаются из офиса: ${n} чел.`,
    reasonFlow: (n) => `панелью Flow пользовались: ${n} чел.`,
    reasonNone: 'за пробный период вы не активировали ни одного места: предлагаем тариф, с которого вы начали',
    recChange: 'Меняйте тариф, добавляйте или убирайте места: сумма ниже пересчитывается сразу.',
    billingMonthly: 'Ежемесячно',
    billingAnnual: 'Ежегодно',
    billingSave: (amount) => `экономия ${amount}`,
    planCeiling: (n) => `до ${n} мест TimeTracker`,
    planCeilingUnlimited: 'места TimeTracker без ограничений',
    seatsTitle: 'Места TimeTracker',
    seatsHelp: 'По одному на каждого сотрудника, отмечающегося с телефона. Оплачиваются отдельно: ни один тариф их не включает.',
    seatsUnit: (price) => `${price} за сотрудника`,
    seatsDecrease: 'На одно место меньше',
    seatsIncrease: 'На одно место больше',
    bumpUp: (plan, n) => `Для ${n} мест нужен Flow ${plan}: мы выбрали его за вас.`,
    bumpDownHint: (plan) => `С таким числом мест хватило бы Flow ${plan}.`,
    bumpDownAction: (plan) => `Перейти на ${plan}`,
    seatsTrimmed: (plan, n) => `Flow ${plan} вмещает ${n} мест: мы установили количество ${n}.`,
    officeTitle: 'Офисные места для отметок',
    officeHelp: 'Для тех, кто отмечается с компьютера, без рабочего телефона.',
    officeAnnualOnly: 'Доступны только при годовой оплате.',
    lineFlow: (plan) => `Flow ${plan}`,
    lineTt: (n) => `Места TimeTracker: ${n}`,
    lineOffice: (n) => `Офисные места: ${n}`,
    totalLabel: 'Итого',
    perYear: 'в год',
    perMonth: 'в месяц',
    vatExcluded: 'без НДС',
    laterNote: 'Места можно добавить в любой момент: вы доплатите только разницу за оставшиеся месяцы.',
    vatLabel: 'ИНН / НДС',
    vatPlaceholder: 'напр. IT01234567890',
    termsPrefix: 'Я прочитал(а) и принимаю',
    termsLink: 'Условия обслуживания',
    privacyPrefix: 'Я прочитал(а)',
    privacyLink: 'Политику конфиденциальности',
    submit: 'Перейти к оплате',
    loading: 'Секунду...',
    missingTenant: 'Неверная ссылка: отсутствует привязка к аккаунту.',
    vatRequired: 'Укажите ИНН / номер НДС.',
    minTermRequired: 'Необходимо отдельно принять условие о минимальном сроке.',
    generic: 'Что-то пошло не так. Попробуйте ещё раз.',
    alreadySubscribed: 'У этого аккаунта уже есть активная подписка.',
  },
};

export function pickLocale(raw: string | null | undefined): UiLocale {
  const value = (raw || '').toLowerCase();
  if (!value) return 'en';
  const base = value.split('-')[0];
  return (UI_LOCALES as string[]).includes(base) ? (base as UiLocale) : 'en';
}
